### ISSUE TITLE
'Dupe' bug?

### ISSUE THREAD

**Issue by Drakoflame** [TheIllusiveC4/Polymorph#1]
#### Versions (Be specific, do not write "latest"):
* Polymorph: 1.15.2-0.1
* Forge: 32.2.9
#### Observed Behavior: 
Duplication in crafting grid (player/crafting table) when shift-clicking from crafting area, if the crafting input has 'one set' (IE: crafting an ingot from 9 nuggets will result in two ingots, but 2 ingots from 18 nuggets has no odd behavior), and other strange duplication issues/item deletion (attempting to craft Leather using RottenFlesh to Leather mod, 4 cleaned flesh and 2 string, crafting recipe had 4 flesh, and 3 sting placed, produced 2 leather, and "deleted" the 3rd string)
#### Expected Behavior: 
Standard output of crafting recipe
#### Steps to Reproduce: 
1. set up a crafting recipe using one set of inputs
2. shift-click the output into your inventory

**Comment by TheIllusiveC4** [comment]
Hmm, odd, I can't reproduce this. At least, with the 9 nuggets -> ingot recipe. If I shift-click the output, it only gives me 1 ingot. Are you in single player? Are you using the normal crafting table? Can you reproduce this with only Polymorph installed?

**Comment by TheIllusiveC4** [comment]
Actually, I was able to reproduce this. I forgot that I myself was not using the normal crafting table as I was testing on FastWorkbench beforehand. This happens with the normal crafting table but not with FastWorkbench installed.
