### ISSUE TITLE
Crash on server 1.16.15

### ISSUE THREAD

**Issue by ModernGamingWorld** [TheIllusiveC4/Polymorph#101]
#### Versions (Be specific, do not write "latest"):
* Polymorph: 1.16.5-0.26
* Forge/Fabric: Forge

Server crashed after Mining a block and it blamed Polymorph

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
https://gist.github.com/ModernGamingWorld/bedb13baa6565610969884b64a3f5f66

**Comment by TheIllusiveC4** [comment]
What kind of block was mined that caused the crash?

**Comment by ModernGamingWorld** [comment]
> What kind of block was mined that caused the crash?

astral Sorcery Block

**Comment by TheIllusiveC4** [comment]
This is a bit of a hard issue to debug. While I've attempted a fix that I think should address the issue, I can't be certain. Please test out the newest version, 0.27, and let me know if you encounter this issue again.

**Comment by nivthefox** [comment]
I was experiencing this, too.  Updating from 0.26 to 0.33 seems to have fixed it.  Just to confirm.
