### ISSUE TITLE
Support for AE2 crafting terminals

### ISSUE THREAD

**Issue by djoveryde** [TheIllusiveC4/Polymorph#103]
**Please describe the new feature or change.**
Currently AE2 crafting terminals don't show the toggle button to switch between item types. Would be great to add it in to support Applied Energistics 2 terminals.

**Please describe why you want this feature.**
Works fine for most terminals, but not AE2 which is a largely used mod.

**Comment by TheIllusiveC4** [comment]
It already does work with AE2. Here's it working in my test instance:

![2021-11-07_13 45 04](https://user-images.githubusercontent.com/29991504/140662981-64c4e139-71e2-42fe-a899-7d223ad1f0f9.png)

If it doesn't work for you, please open a new issue and fill out the bug report template.

**Comment by djoveryde** [comment]
Hmm its not working for me. Although i'm having to use 0.25 right now due to 26 and 27 crashing my server on player join.
Is there something I need to do?

**Comment by TheIllusiveC4** [comment]
AE2 support was added in 0.26.

**Comment by djoveryde** [comment]
That'll be it then. I'll have to wait for it to be fixed as I also have refined storage mod.
