### ISSUE TITLE
Polymorph and FastWorkbench Minus Replacement Incompatibility

### ISSUE THREAD

**Issue by Reshy** [TheIllusiveC4/Polymorph#104]
Using Polymorph and FastWorkbench Minus Replacement prevents the polymorph icon from appearing on the crafting menus.

**Comment by Reshy** [comment]
Looks like the bug still persists.
![2021-11-10_20 39 11](https://user-images.githubusercontent.com/2096384/141238170-a4d6319a-87e7-4200-ae02-68a7792c7bcb.png)

**Comment by TheIllusiveC4** [comment]
I'm not sure what you mean, your screenshot shows an empty crafting grid (which means no valid recipes).
