### ISSUE TITLE
Sophisticated Backpacks auto-smelting compatibility

### ISSUE THREAD

**Issue by Kalastra** [TheIllusiveC4/Polymorph#105]
#### Versions:
* Polymorph: 1.16.5-0.30
* Forge: 36.2.9

#### Observed Behavior:

The auto-smelting upgrade for Sophisticated Backpacks does not work with Polymorph installed (see: https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/300). The items enter the correct slots but do not start smelting.

#### Expected Behavior:

Fuel is expended to smelt the objects in the upper slot.

#### Steps to Reproduce:
1. Install Sophisticated Backpacks (sophisticatedbackpacks-1.16.5-3.11.1.390.jar) and Polymorph (polymorph-forge-1.16.5-0.30.jar) under Forge 36.2.9
2. Add a smelting upgrade to the pack and add a smeltable object + fuel

**Comment by TheIllusiveC4** [comment]
Does this happen with the Smelting upgrade too or just the Auto-Smelting upgrade?

**Comment by Kalastra** [comment]
Only the auto-smelter, it turns out. The un-upgraded version works as expected.
