### ISSUE TITLE
Crash in Simple Storage Network Integration

### ISSUE THREAD

**Issue by phit** [TheIllusiveC4/Polymorph#11]
#### Versions (Be specific, do not write "latest"):
* Polymorph: polymorph-FORGE-1.15.2-0.3.jar 
* Forge: forge-1.15.2-31.2.27
* SSN: SimpleStorageNetwork-1.15.2-1.0.1
#### Observed Behavior:
server crash, to quote the player that triggered it

> the crash was me. Was building multiple torches in the crafting interface of Simple Storage Network and it seemed to crash right as i was making a full stack at once

...

Crash Log: https://gist.github.com/phit/f8daabbf1bd0123eca0c76b458a71b28

**Comment by TheIllusiveC4** [comment]
I can't reproduce this. Crafting a full stack of torches multiple times in the Simple Storage Network Request Table and the Crafting Remote does not produce any errors or crashes. Can the person reproduce this bug reliably?

**Comment by phit** [comment]
seems like a remapping issue in the production jar, the field should be `field_75151_b` not `inventorySlots` in the crash report
that also explains `java.lang.NoSuchFieldError:`

**Comment by TheIllusiveC4** [comment]
While that would make sense, I am using the production jar to test this and I can't reproduce this behavior. That being said, I know Simple Storage Network went through a refactor after the last Polymorph release so maybe some wires are getting crossed somehow in that regard. I'll update the integration's Simple Storage Network version and see if that fixes it in a new build.

**Comment by phit** [comment]
I can't reproduce it either with those instructions :/ It just happened again on the same server, gonna recompile whats on Github and hope for the best.

**Comment by phit** [comment]
Welp, I recompiled with latest and then decompiled the Jar and compared it  with your release. No changes.. I'm quite confused how `NoSuchFieldError` is possible `ContainerNetwork extends Container` and there's an instanceof check in the calling method aswell https://github.com/TheIllusiveC4/Polymorph/blob/master/src/main/java/top/theillusivec4/polymorph/common/network/client/CPacketTransferRecipe.java#L81

**Comment by phit** [comment]
welp that didn't fix it, just got the same crash with a patched jar, gonna add some debugging what container is being called

**Comment by TheIllusiveC4** [comment]
Oh that's a shame. I do have a couple ideas for a possible fix, but it'd be hard to verify their efficacy without being able to reproduce this myself. Since you seem to have gotten the same crash again, do you have reliable reproduction steps or did it just happen by chance?

**Comment by phit** [comment]
Just 20 players being online over a couple of hours it will happen eventually, they all seem to be just shift crafting various things with multiple output options when it happens.

I'll try again to find a reliable repro tomorrow.

**Comment by Vaelzan** [comment]
I'm not sure if the report here will help you to reproduce it or not, but here it is (using Valhelsia 2.2.4, in case you want to use an identical environment). https://github.com/ValhelsiaTeam/Valhelsia/issues/149

**Comment by TheIllusiveC4** [comment]
Sorry for the delay. I haven't had much luck reproducing this issue so I can't say for sure if my attempted fix solves it. Just let me know if the issue still occurs in the 0.4 update.

**Comment by phit** [comment]
This specific issues seems to be resolved. Thanks!
