### ISSUE TITLE
polymorph button does not appear when replaymod is installed

### ISSUE THREAD

**Issue by Minionade** [TheIllusiveC4/Polymorph#111]
#### Versions (Be specific, do not write "latest"):
* Polymorph: 0.0.14
* Forge/Fabric: Fabric 0.12.5
* Conflicting Mod: Replay Mod 2.6.1
#### Observed Behavior: 
With ReplayMod installed, the Polymorph button does not appear when crafting with conflicting recipes.
#### Expected Behavior: 
Polymorph button should appear when crafting with conflicting recipes
#### Steps to Reproduce:
1. Load an instance with Polymorph, button appears for conflicts.
2. Add ReplayMod, button stops appearing entirely.

**Comment by TheIllusiveC4** [comment]
I was unable to reproduce this, loading these versions of the mods I was able to get the button to appear as usual. Regardless, try out the newest version of Polymorph (which was rewritten for the new update) and the newest version of Replay Mod and let me know if the issue persists for you.
