### ISSUE TITLE
Client side crash when rendering GUI from Draconic's fusion crafting core

### ISSUE THREAD

**Issue by Kzeroko** [TheIllusiveC4/Polymorph#112]
#### Versions (Be specific, do not write "latest"):
* Polymorph: polymorph-forge-1.16.5-0.31
* Forge/Fabric: Forge 
#### Steps to Reproduce: 
1. Install polymorph with draconic evolution 1.16
2. Open Fusion Crafting Core GUI
[crash-2021-11-28_03.26.16-client.txt](https://github.com/TheIllusiveC4/Polymorph/files/7612829/crash-2021-11-28_03.26.16-client.txt)

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
https://www.toptal.com/developers/hastebin/cacebaquto.rb

**Comment by TheIllusiveC4** [comment]
Update to Polymorph 1.16.5-0.33+.
