### ISSUE TITLE
Fastbench

### ISSUE THREAD

**Issue by Purple1984** [TheIllusiveC4/Polymorph#113]
When I try to start the game, it always says "polymorph only supports Fastbench 4.6.0 or above Currently, Fastbench is 4.5.1".

I am on Minecraft 1.16.5 on forge version.

I have looked and looked and I don't think this mod exists.
I have also checked my mod folder for it as well.

**Comment by TheIllusiveC4** [comment]
This mod: https://www.curseforge.com/minecraft/mc-mods/fastworkbench

You need to update your FastWorkbench version.
