### ISSUE TITLE
Crash with GenesisSMP Modpack

### ISSUE THREAD

**Issue by Wolfy8198** [TheIllusiveC4/Polymorph#115]
* Polymorph: polymorph-fabric-0.0.13-1.16.5.jar
* Forge/Fabric: fabric 0.11.7
#### Steps to Reproduce:
1. Install GenesisSMP Modpack from CurseForge
2. Add Polymorph (I'm the creator of the modpack, there were some conflicting recipes and I want to solve that with this mod in our last mod update)
3. Run the modpack
...
**NOTE** All mods in the modpack are required except the client side mods, excluding WTHIT, Tweakeroo, and Inventory Profiles Next.
...
Crash Log: None given. "An unexpected error occurred and the game crashed. We're sorry for the inconvenience. Exit Code: 0"

**Comment by Wolfy8198** [comment]
Opened the console thing while the modpack was opening and got this fatal error:
https://pastebin.com/89aVHfZA

**Comment by TheIllusiveC4** [comment]
I'm not completely sure what's going on here because there's so many mods; however, I do know that in my testing I can just add Cardinal Components API by itself without Polymorph and still get this same crash. So this is likely a CCA issue, not Polymorph.
