### ISSUE TITLE
fix this...

### ISSUE THREAD

**Issue by An0yim0us666** [TheIllusiveC4/Polymorph#116]
i keep getting this in my crashlog when starting minecraft (1.16.5 fabric)

[11:43:39] [ForkJoinPool-1-worker-1/WARN]: The mod "cardinal-components-entity" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[11:43:39] [ForkJoinPool-1-worker-5/WARN]: The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11

please fix this...

**Comment by K0-RR** [comment]
Are you serious? It's not a Polymorph issue...

**Comment by An0yim0us666** [comment]
then why do those things dissapear when i remove polymorph

**Comment by itsdinkd** [comment]
because its a cardinal components issue lmfao Polymorph just uses its API. and also, that **warning** does not affect anything

**Comment by TheIllusiveC4** [comment]
I'm not sure if this was really erroneous or due to an outdated CCA or something, but I've updated the 1.16.5 Polymorph version's dependencies in the latest update which should rule out anything on Polymorph's side regarding this.
