### ISSUE TITLE
Change fabric.mod.json to support =>1.17. 

### ISSUE THREAD

**Issue by TheRanker** [TheIllusiveC4/Polymorph#121]
**Please describe the new feature or change.**
Update mod to accept 1.18.1 on curseforge and edit the fabric.mod.json to change "minecraft": "1.17.x" to "minecraft": ">=1.17").

Tested in 1.18.1 enviroment with 226 mods. Fixed all my issues.  

**Please describe why you want this feature.**

Unable to add to modpack cause curseforge version fails to load. 

Fabric

**Comment by TheIllusiveC4** [comment]
A proper 1.18.1 update will be released soon.
