### ISSUE TITLE
1.18.1 Polymorph crashes while opening furance

### ISSUE THREAD

**Issue by BugmanBugman** [TheIllusiveC4/Polymorph#126]
#### Versions (Be specific, do not write "latest"):
* Polymorph: -1.18.1-0.33
* Forge/Fabric: 39.0.9
#### Steps to Reproduce:
1. open up furnace
2. boom
3. crash
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
https://bytebin.lucko.me/4Z20CkUuoM

**Comment by TheIllusiveC4** [comment]
Duplicate of https://github.com/TheIllusiveC4/Polymorph/issues/122
