### ISSUE TITLE
Crash from conflict between SophisticatedBackpacks and Polymorph 

### ISSUE THREAD

**Issue by ModernGamingWorld** [TheIllusiveC4/Polymorph#127]
https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/374

**Comment by Potatomonium** [comment]
I'm also getting this crash when I think it calls the Smelter upgrade
https://pastebin.com/y1dcTQeq

**Comment by magcicada** [comment]
Also crash at 1.16.5 version, plz update 1.16.5. @TheIllusiveC4
