### ISSUE TITLE
Mod requires AE2 to run

### ISSUE THREAD

**Issue by DraLUSAD** [TheIllusiveC4/Polymorph#131]
Yet, it doesn't state this on the mod page
![Screenshot 2022-01-03 105846](https://user-images.githubusercontent.com/57923958/147923181-a156ae7c-01f1-4a8f-aec7-a5745ac4c239.png)
,

**Comment by TheIllusiveC4** [comment]
Whoops, that's not right. I'll fix that momentarily.
