### ISSUE TITLE
[1.16.5] Cross-mod compatability wtih the Storage actuator GUI (Occultism)

### ISSUE THREAD

**Issue by Shibva** [TheIllusiveC4/Polymorph#132]
**Please describe the new feature or change.**
as the title insitsts, add support fo the crafting/storage GUI added by Occultism's Dimensional Storage Actuator

**Please describe why you want this feature.**
it would be nice and it makes crafting conflicts easier to handle since it does have a crafting table in it and it does not seem to have polymorph "recipe shift" in it

to ensure that both things can work out, Ill also make a report on their end linking to this issue

**Comment by klikli-dev** [comment]
@TheIllusiveC4 Based on #107 I'm not sure what I can/should do on my end, but if there is, please let me know. Integration would be neat as more and more people "complain" about the lack of polymorph in my storage UI :D

**Comment by Shibva** [comment]
Thanks
