### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Idefkftt** [TheIllusiveC4/Polymorph#133]
#### Versions (Be specific, do not write "latest"):
* Polymorph: 1.18.1-0.35
* Forge/Fabric: 39.0.10
#### Steps to Reproduce:
1. Load mods
2. Load into world
3. Open inventory
4. Crash

Crash Log: (https://crashy.net/MGmsAhUU7j6T8vqkKr6d)

It looks like it couldn't read something in AE2 so I'm not sure if this would be classed as a Polymorph issue or an AE2 issue but I will be posting it on both pages just in case.  If this is clearly an AE2 issue then I apologize for the wasted time.

**Comment by TheIllusiveC4** [comment]
Update to the latest AE2 (10.0.0-beta.3).
