### ISSUE TITLE
Shapeless crafting recipe conflict not being recognised 

### ISSUE THREAD

**Issue by Aaron995** [TheIllusiveC4/Polymorph#134]
#### Versions (Be specific, do not write "latest"):
* Polymorph: 0.0.18-1.18.1
* Fabric: 0.12.12
#### Observed Behavior: Having a conflict of a shapeless crafting recipe from both ValleyCraft and Farmers Delight for a milk bottle. Their recipe is both the same ingredients but Polymorph isn't allowing me to choose what to craft when I put the ingredients in. 
Their recipes are: 
https://bitbucket.org/n-horyzon/farmers-delight-fabric/src/develop/src/main/resources/data/farmersdelight/recipes/milk_bottle.json
https://github.com/ValleyCraft-Dev-Team/ValleyCraft/blob/main/src/main/resources/data/valley/recipes/milk_bottle.json

#### Steps to Reproduce:
1. Install Polymorph, Farmers DElight and ValleyCraft
2. Obtain a bucket of milk and 3 glass bottles
3. Try to craft a bottle of milk but only getting 1 choice

**Comment by TheIllusiveC4** [comment]
I can't reproduce, installing those two mods I still get the choice between the two.

Can you reproduce this with _only_ Farmer's Delight, ValleyCraft, and Polymorph installed? Are you using the vanilla crafting table or something else?

**Comment by Aaron995** [comment]
Hi I found the issue! 

FastBench: https://www.curseforge.com/minecraft/mc-mods/fastbench-for-fabric
seems to break something with polymorph
