### ISSUE TITLE
No Quark alternative for Astral Sorcery marble

### ISSUE THREAD

**Issue by Clownhustler** [TheIllusiveC4/Polymorph#135]
#### Versions (Be specific, do not write "latest"): FTB Endeavour
* Polymorph: 1.16.5-0.37
* Forge/Fabric: Forge: Forge 36.2.19
* FTB Endeavour 1.8
* Minecraft 1.16.5
#### Steps to Reproduce: 
1. Place Astral Sorcery marble in crafting table 2x2

Further note: command "/polymorph conflicts" is not recognized by console. Even though Polymorph appears in mod list and has reported no issues.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
no crash

**Comment by TheIllusiveC4** [comment]
This is not a bug. The Quark recipe for Polished Marble specifically only takes Quark marble, nothing else. If you want this to work, you need to make a new recipe yourself for Quark Polished Marble that also accepts Astral Sorcery Marble.

> Further note: command "/polymorph conflicts" is not recognized by console. Even though Polymorph appears in mod list and has reported no issues.

You might need to go into Creative mod first, or create a new world with Cheats enabled. You need elevated permissions to run the command.
