### ISSUE TITLE
Not able to choose Ender Block craft

### ISSUE THREAD

**Issue by Wolfy8198** [TheIllusiveC4/Polymorph#136]
#### Versions (Be specific, do not write "latest"):
* Polymorph: polymorph-fabric-0.0.18-1.18.1.jar
* Forge/Fabric: Fabric 0.12.12
#### Observed Behavior:
When trying to craft an Ender Block from BetterEnd, it has a conflict with the Ender Pearl block from Architect's Pallete Fabric, If I try to choose the Ender Block, the block in the output slot of the crafting table stays an Ender Pearl Block.
#### Expected Behavior:
Ender Pearl Block changes to Ender Block

**Comment by TheIllusiveC4** [comment]
Do you have FastBench installed?

**Comment by Wolfy8198** [comment]
No

**Comment by Wolfy8198** [comment]
I do have REI installed, though, if that makes any difference

**Comment by TheIllusiveC4** [comment]
Just making sure I got this right, you _can_ choose the Ender Block but the output never actually changes right?

Does this still happen if you test this with _only_ Polymorph, BetterEnd, and Architect's Palette installed?

**Comment by Wolfy8198** [comment]
Give me like 10 minutes, I didn't try that because all of those mods are still in BETA and I have to download them manually

**Comment by Wolfy8198** [comment]
I just checked, and yes, it still happens with only those mods and their dependencies installed

**Comment by Wolfy8198** [comment]
Here's the mods I have installed in the test profile.
![Screenshot 2022-01-11 024652](https://user-images.githubusercontent.com/64490202/148901751-02476b85-d693-40e4-ae78-b0e48faf4806.png)

**Comment by TheIllusiveC4** [comment]
I've been doing some investigating, and I think this is a niche issue with BetterEnd. Now, I'm not super familiar with their code-base so I could have easily missed something, but it seems like they're doing some non-standard recipe registration and Polymorph does not receive any recipe when it tries to call this when selecting their recipe:

https://github.com/TheIllusiveC4/Polymorph/blob/99fcab89ed59d6b3534c0c40cb03da60b6b3c146/fabric/src/main/java/top/theillusivec4/polymorph/common/network/PolymorphNetwork.java#L36

I'll try to do some more investigating on my end, but for now it seems likely that there is no fix that I can do for this.

**Comment by TheIllusiveC4** [comment]
I've made a bug report on BetterEnd's issue tracker in order to better investigate the issue. Please follow any potential updates there as well.

**Comment by TheIllusiveC4** [comment]
This issue should be resolved now as of the latest BCLib release (1.2.3+).
