### ISSUE TITLE
Crashing On Startup

### ISSUE THREAD

**Issue by MyelinSchroder** [TheIllusiveC4/Polymorph#141]
#### Versions (Be specific, do not write "latest"):
* Polymorph: 1.18.1-0.36 
* Forge/Fabric: Forge 39.0.5
#### Steps to Reproduce: Adding Polymorph to my pack (All The Mods 7, plus I added Cyclic 1.18.1-1.6.7 , Storage Drawers 1.18.1-10.0.1 , Explorer's Compass 1.18.1-1.1.2 , Veinmining 1.18.1-0.15 , and Notes 1.18.1-1.2.4
2. Launch the pack
3. Crash
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
https://paste.ee/p/ycjqN

**Comment by TheIllusiveC4** [comment]
> net.minecraftforge.fml.ModLoadingException: Mod §epolymorph§r only supports §3sophisticatedbackpacks§r §o1.18.1-3.15.0 or above§r
§7Currently, §3sophisticatedbackpacks§r§7 is §o1.18-3.12.1.433

Update Sophisticated Backpacks to 3.15.0+.

**Comment by MyelinSchroder** [comment]
Is there a way to keep the mods in a pack up to date without checking each one manually for updates? Version checker doesn't seem to be updated for 1.18
