### ISSUE TITLE
Support for Better Nether/Better end/Blockus

### ISSUE THREAD

**Issue by CrusaderRabbit** [TheIllusiveC4/Polymorph#145]
Better Nether and Blockus have a conflict between nether sandstone. I am not sure if there are any other conflicts between these three mods but included them in case

**Comment by TheIllusiveC4** [comment]
As far as I can tell, the Soul Sandstone recipes are identified as a conflict by Polymorph. However, choosing an output seems to be bugged in this particular instance. So I'm going to re-categorize this as a bug and investigate accordingly.

**Comment by CrusaderRabbit** [comment]
You can close this. I got it working myself via config and better nether dev team said the recipes were re-added in a later version so it was more a fault with that mod I think.
