### ISSUE TITLE
Support for Crafting Tweaks

### ISSUE THREAD

**Issue by emanuele246gi** [TheIllusiveC4/Polymorph#148]
**Please describe the new feature or change.**
Support for Crafting Tweaks

**Please describe why you want this feature.**
The Polymorph's icon doesn't always appear when when I use this mod

**Comment by TheIllusiveC4** [comment]
I just tested it with Crafting Tweaks and it works fine. What do you mean by "doesn't always appear"? Which recipe conflicts specifically are you trying when the icon doesn't appear? Please note that the icon only shows up when a recipe conflict is detected.

**Comment by emanuele246gi** [comment]
Sorry, my bad, it was another mod which I didn't add in my pack, not Polymorph, thank you for the response tho. Keep up with the good work on this mod ^^
