### ISSUE TITLE
Mod Conflict not resolving

### ISSUE THREAD

**Issue by erragar** [TheIllusiveC4/Polymorph#15]
My Fiance came up with a Modpack that uses the following two mods 

[https://www.curseforge.com/minecraft/mc-mods/bag-of-yurting](url)

and 

[https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator](url)

The recipe for a Bag of Yurting and a White Elevator Block are the same, but we cannot select between the two even selecting the elevator block in the pop up menu that you've provided. Is there some way to relieve this issue on our end? We'd love to have these mods in at the same time.

**Comment by TheIllusiveC4** [comment]
Please give me the version numbers for Bag of Yurting, OpenBlocks Elevator, Polymorph, and Forge.

In addition, what crafting methods have you tried? If you have only tried the vanilla crafting table, and you have FastWorkbench installed, then the 0.7 version of Polymorph that I just released a few minutes ago may solve your issue.

**Comment by erragar** [comment]
Here are the versions first, and my Fiance is going to try 0.7. I'll give you a progress report asap

Bag of Yurting 1.0.0.1
OpenBlocks Elevators 1.15.2-1.7.1
Polymorh FORGE  1.15.2 - 0.6
Forge: 31.2.31

**Comment by TheIllusiveC4** [comment]
Any update on this?

**Comment by erragar** [comment]
My apologies on this. We were giving it a good deal a testing, just to make sure one instance wasn't definitive. Yes, this issues seems to have been fixed by updating. Thank you for your initial swift response and looking out for this kinda stuff :D
