### ISSUE TITLE
CRASHING: Interaction with Refined Storage causes crash

### ISSUE THREAD

**Issue by aerialspring** [TheIllusiveC4/Polymorph#150]
#### Versions (Be specific, do not write "latest"):
* Polymorph: 0.37 and 0.38 (updating did not fix issue)
* Forge/Fabric: 39.0.79 and 39.0.85 (updating did not fix issue)
#### Steps to Reproduce:
1. Break RS grid by any means - hand, pickaxe, magic, etc.
2.
3.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/). 
https://pastebin.com/1BcMt6nk

I have also posted a bug report to RS regarding this interaction.

**Comment by aerialspring** [comment]
Disabling Polymorph integration for RS and RS addons resolves the crash, but we would like to have this functionality available in RS crafting ideally.

**Comment by aerialspring** [comment]
Has this been fixed?

**Comment by TheIllusiveC4** [comment]
Should be, you can test it once CF approves the 0.39 version.

**Comment by aerialspring** [comment]
Wonderful!! Thank you :)
