### ISSUE TITLE
Flickering of Polymorph button if Tag output is introduced

### ISSUE THREAD

**Issue by Toma400** [TheIllusiveC4/Polymorph#151]
#### Versions (Be specific, do not write "latest"):
* Polymorph: 0.38
* Forge/Fabric: Forge 1.16.5
#### Steps to Reproduce:
1. Install Immersive Engineering, Create and Tinker's Construct alongside Polymorph
2. Try to smelt some non-exclusive ores, such as copper ore
3. See button flickering

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by TheIllusiveC4** [comment]
I cannot reproduce your issue. Here are my steps:

1. I installed Immersive Engineering, Create, and Tinkers' Construct alongside Polymorph.
2. I obtained some Tinkers' Construct Copper Ore.
3. I placed the ore into a vanilla Furnace.
4. The button does not flicker at all, as expected. I can also choose between Create and Tinkers' Construct Copper Ingots as the output successfully.

Are you able to reproduce this issue with _only_ these mods installed? If not, this is likely a mod conflict and you'll need to find the mod that is causing the issue before I can investigate further.
