### ISSUE TITLE
Crash with World Generation

### ISSUE THREAD

**Issue by Cicopath** [TheIllusiveC4/Polymorph#155]
#### Versions (Be specific, do not write "latest"):
* Polymorph: 1.18.1-0.39
* Forge: 1.18.1-39.1.1
#### Steps to Reproduce:
1. Install all of the mods with their specified versions in the crash log. Here is a pastebin of the mods used, including Forge: https://pastebin.com/upv5QgM1
2. Start a new world.
3. Create a Nether Portal, and enter the portal.
4. After successfully entering the Nether, wait for the new chunks to load. If nothing occurs, travel around until a crash (specifically related to generation) occurs.

Crash Log: https://pastebin.com/TejfUwZG

**Additional Comments**
I have attempted to try mods individually. For example, I tested just Simple Ores, Netherrocks, SimpleCoreLib, and Polymorph. After encountering no crashes, I added TerraBlender, Biomes O' Plenty, OTBYG, Mana and Artifice, Patchouli, GeckoLib, Curios, The Graveyard, The Graveyard Biomes, and Occultism; yet, still no crash occurred. This is unusual, as removing just Polymorph or just Netherrocks from the list of mods in the mod folder solved the issue. On a separate note, please forgive me in regards to having to download many mods in recreating this crash. I fear it may be a specific conflict.

After learning about this crash, my brother had tested a new world with all of the exact same mods. However, no crash occurred on his end. This further proves my fear and how unusual this crash is.

I have already reported this to the author of TerraBlender via Discord. However, they stated the crash is not a, "TerraBlender crash," as crashes from TerraBlender provide pretty explicit logs. I was told that Polymorph could be the cause, hence why I am creating this report.

If no solution is found, yet I have an idea of what (mod) may be causing this crash, I will use this report as a reference.

**Comment by Cicopath** [comment]
This was a crash log previous to the crash log posted above: https://pastebin.com/9z4pvwkS

**Comment by TheIllusiveC4** [comment]
> I have already reported this to the author of TerraBlender via Discord. However, they stated the crash is not a, "TerraBlender crash," as crashes from TerraBlender provide pretty explicit logs. I was told that Polymorph could be the cause, hence why I am creating this report.

When you reported it to them, did you send them both of your crash logs or just one of them? If so, which one? I ask because the second crash report is fairly vague, but the first crash report (the one you included in your initial post) is fairly explicit and shows that it's crashing from a TerraBlender method.

**Comment by Cicopath** [comment]
The one I included in my initial post was half an hour ago. The second one was created hours ago, which is the one I sent them. Should I send the TerraBlender author the crashlog I initially posted here?

**Comment by TheIllusiveC4** [comment]
Yes, I recommend sending them the initial crash log you posted here. It should be fairly straightforward to see that it is a TerraBlender issue, but perhaps the author has other insights that I am not seeing.

**Comment by Cicopath** [comment]
Alright, will do.

I also wanted to provide an update: I created a new world with the exact mods, and oddly enough, no crash is occurring in the Nether. I don't know why or how. I will test with that specific seed in a new world.

Thank you for your responses!

**Comment by TheIllusiveC4** [comment]
I'll close this issue for now but if any other information comes up that warrants my investigation again, feel free to comment again and I'll re-open it.
