### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by UsernameNotActive** [TheIllusiveC4/Polymorph#157]
#### Versions (Be specific, do not write "latest"):
* Polymorph: polymorph-forge-1.18.1-0.34
* Forge/Fabric: forge 1.18.1
#### Steps to Reproduce:
1. have at least 1 datapack
2.
3.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by TheIllusiveC4** [comment]
I cannot reproduce your issue. I always test with datapacks as the way I implement conflicts into my environment, so it would be very difficult for the mod to have a bug of this general nature.

1. Your Polymorph version is a bit outdated, try updating to the latest version.
2. Are you sure that your datapacks work?
3. What recipe conflict did you test in the crafting table?
4. What kind of crafting table did you use?
5. Did you have other mods installed? If so, try reproducing this issue without anything except Polymorph installed.

**Comment by UsernameNotActive** [comment]
I updated the polymorph mod to the latest version and I still have this issue. I tried making a new world without any datapacks and the polymorph mod does work with all the other mods I have installed, however when I add a datapack it stops working. For reference I am using the vanilla tweaks and technical enchants datapack.

**Comment by TheIllusiveC4** [comment]
Okay, please answer the rest of the questions and some additional ones:

1. What recipe conflict did you test in the crafting table?
2. What kind of crafting table did you use?
3. Can you link to the datapacks you installed? Better yet, can you share the exact datapacks you are using?

**Comment by UsernameNotActive** [comment]
The recipe conflict I tried was the deepslate furnace from the Quark mod. I used a normal crafting table, however I have the fast workbench mod installed. The datapacks I used are technical enchants, better underwater ruins, blaze and caves advancement pack, and some vanilla tweaks datapack: anti-enderman grief, armor statues, more mob heads, custom nether portals and fast leaf decay.
I tried the mod with each datapack individually and the problem showed up with all of them. 
I don't know what's wrong, but I'm having the same problem with the aquacultre 2 mod, but all the other mods work perfectly fine?

**Comment by TheIllusiveC4** [comment]
I've tried it with the Vanilla Tweaks datapacks that you mentioned. All of them work fine, Polymorph still functions normally. I even did it with the Deepslate Furnace conflict with Quark installed, alongside Fast Workbench and the normal crafting table. Everything works fine. So there's something else going on here.

Please remove all other mods except for Quark and Polymorph and then test it again to see if it's a mod conflict.

**Comment by UsernameNotActive** [comment]
I still have the issue even without the other mods as long as I have a datapack enabled in my world

https://user-images.githubusercontent.com/77725997/156911817-687a2a4a-2288-4427-87b8-a31484bf1909.MOV

.

**Comment by TheIllusiveC4** [comment]
I can see that the button actually does show up for a split second before disappearing. This is important because it means that it is working, but _something_ is interrupting the process. Although I'm not sure what that is at this point. 

Okay, so basically, if you have only Quark and Polymorph installed with no other mods, and any datapack, it stops working right? And you're certain there's nothing else special about your world, nothing else that has been added or changed? Does this happen if you make a new world and add the datapack to that one?

**Comment by UsernameNotActive** [comment]
The video was film in a new  world that I just created. whether I create the world with the datapack or add a datapack later on, the problem arises but when I remove all datapacks, the mod starts working properly.
Do you think it might be a ressource pack that is causing trouble?

**Comment by UsernameNotActive** [comment]
Nope, tested without ressource packs and still not working properly.

**Comment by TheIllusiveC4** [comment]
Okay, can you try it again with nothing else installed and then afterwards give me your `latest.log` file for the session?

**Comment by UsernameNotActive** [comment]
Here,
[latest.log](https://github.com/TheIllusiveC4/Polymorph/files/8195007/latest.log)

**Comment by TheIllusiveC4** [comment]
Hm, unfortunately nothing seems to pop out at me from the log. Everything seems fine.

One last test. Remove all the other datapacks and try this datapack by itself:
[test.zip](https://github.com/TheIllusiveC4/Polymorph/files/8203022/test.zip)

This is the datapack I use to test Polymorph and it definitely is compatible. If it works, then something is wrong with the rest of your datapacks. If it still doesn't work, then something else is going on with your instance but I've run out of ideas on what that could possibly be.

**Comment by UsernameNotActive** [comment]
It works so the problem is with the other datapacks. I will try contacting their creators to see if they can resolve the issue on their end. Thank you for spending time helping me.
