### ISSUE TITLE
Smoker blast furnace synthesis can still conflict

### ISSUE THREAD

**Issue by liuzhi123hao** [TheIllusiveC4/Polymorph#159]
#### Versions (Be specific, do not write "latest"):
* Polymorph:
* Forge/Fabric:
#### Steps to Reproduce:
1.
2.
3.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by TheIllusiveC4** [comment]
Can you please fill out the bug report with the version numbers and reproduction steps? I'll need to know this information so that I can see what you're talking about and replicate it on my end.
