### ISSUE TITLE
Oh The Biomes You'll Go (BYG) Compatability

### ISSUE THREAD

**Issue by Darkfiend009** [TheIllusiveC4/Polymorph#16]
**Please describe the new feature or change.**
Requesting support for crafting tables made of the different woods from the mod "Oh The Biomes You'll Go." (BYG)
https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go

**Please describe why you want this feature.**
BYG adds crafting table variants based on the different woods found in the mod. When trying to craft an item using Polymorph and a crafting table made of the wood from BYG, the output slot is blank. You can still click the output slot to get the item you are trying to craft. However, it is invisible until you click to get the crafted item.

If you need a test environment, you can download my current modpack, Parity: https://www.curseforge.com/minecraft/modpacks/parity

**Comment by TheIllusiveC4** [comment]
Works fine for me. Am I missing something perhaps? Also, this is more like a bug than a feature request, so can you provide version numbers and reproduction steps?

![2020-07-22_14 01 52](https://user-images.githubusercontent.com/29991504/88228413-000d9300-cc24-11ea-9b65-983bbc8cb8a2.png)

**Comment by Darkfiend009** [comment]
I apologize for the lack of clarity. It happens when you are using any of the variant crafting tables as the main crafting table to craft something else.

So, for instance in your picture. You create that crafting table, place it down in the world, and use it functionally as a crafting table to craft another item or block.

**Comment by TheIllusiveC4** [comment]
Well I can reproduce this now, so I'll look into it.

**Comment by Darkfiend009** [comment]
Thank you for this mod and your incredibly fast response and fix! I'll be adding the update to my modpack tomorrow!
