### ISSUE TITLE
Crafting/Smelting poly options not showing up for egg and book

### ISSUE THREAD

**Issue by TamedBologna** [TheIllusiveC4/Polymorph#164]
#### Versions (Be specific, do not write "latest"):
* Polymorph: 0.0.20
* Forge/Fabric: Fabric 0.13.3
#### Observed Behavior:
list start of installed mods in question
polymorph(theillusivec4), patchouli(williewillus), mcdoom(azuredoomc), mythic mounts(chirpycricket_). and egg to capture(jtl_elisa), better animals plus(itsmeow_), additional additions(dqu1jjj)
list end
1.when trying to smelt a Minecraft egg, to get a capture egg from jtl_elisas mod, the poly button does not show up in the furnace and can only make a fried egg from additional additions, which **toggled the food in aa mod,** (edit: which I then went into the config of aa and turned off food hoping poly button would show) then makes a fried egg from better animals plus without the poly button still.
2. when trying to make the **book from mythic mount mod by patchouli**(edit: the patchouli book of the mythic mounts mod that the author made inside the patchouli mod) that was most recently added in chirpycrikets update, the only option is to get azuredooms patchouli book and no poly button. :(
#### Steps to Reproduce:
1. add coal, furnace, crafting table, book, gunpowder, egg to inventory
2.place coal and egg to furnace, no poly button. 
3.place gunpowder and book in crafting table, no poly button
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
no crash

**Comment by TheIllusiveC4** [comment]
Did you have only those mods installed or were there more? If not, can you reproduce this with only those mods you listed?

**Comment by TamedBologna** [comment]
sorry to waste your time, roughly enough items gives a recipe for an item that you get through interacting with a mob, so not a actual recipe but just a blip. anyways your mod is not the problem I made the typical error of using the mods wrong. thank you for your time.
