### ISSUE TITLE
Minecraft Crashes from Launcher

### ISSUE THREAD

**Issue by JSmurf11** [TheIllusiveC4/Polymorph#165]
When I added polymorph-forge-1.18.1-0.4.3 my Minecraft doesn't even open to the Mojang loading screen (with the bar) it immediately gives me a crash report. Is there a way to fix this? 

Crash Report: https://pastebin.com/73z137bd

**Comment by TheIllusiveC4** [comment]
Polymorph isn't in the crash log at all, your report says it's crashing from HammerLib.
