### ISSUE TITLE
 java.lang.IllegalStateException

### ISSUE THREAD

**Issue by VaelophisNyx** [TheIllusiveC4/Polymorph#166]
#### Versions (Be specific, do not write "latest"):
* Polymorph: 0.0.20
* Fabric: 0.13.3
#### Observed Behavior: Crashes on load with this particular mod set. Mods cannot be changed, as they are the mods from a server's mod list. Note: This crash does not occur for other users with the same mods. Reporting for another user, so testing is not exactly something I could do.
[latest (2).log](https://github.com/TheIllusiveC4/Polymorph/files/8545884/latest.2.log)

**Comment by VaelophisNyx** [comment]
further information: User in question has done two clean installs of both all involved mods & Fabric, and minecraft itself. Still results in a crash on main-menu load. First error is Polymorph related, further errors are less clear

**Comment by TheIllusiveC4** [comment]
This seems like an error with their `polymorph-integrations.json` configuration file. Please tell the user to either delete the configuration file so it can be regenerated normally or fix the formatting error in the file.
