### ISSUE TITLE
The game crashed whilst unexpected error Error: java.lang.NullPointerException:

### ISSUE THREAD

**Issue by tindin** [TheIllusiveC4/Polymorph#167]
#### Versions (Be specific, do not write "latest"):
* Polymorph:
* Forge
#### Observed Behavior:
 used a furnace and client crashes

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
https://pastebin.com/A0cqe38b

**Comment by TheIllusiveC4** [comment]
Did you try this in single player or multiplayer? If multiplayer, did you make sure to install this mod on both the client and server?

Does this issue occur if you have ONLY Polymorph installed?

**Comment by NielsPilgaard** [comment]
This has recently happened in E8, with [polymorph-forge-1.18.2-0.45.jar](https://www.curseforge.com/minecraft/mc-mods/polymorph/files/3995029).

Cause: 
> When a player gets AFK kicked from the server, their modpack fully crashes and shuts down.
Leaving the server and rejoining it works without an issue, it appears to only happen when getting kicked for some reason.

Polymorph was present on both client and server.

Linked issue: https://github.com/EnigmaticaModpacks/Enigmatica8/issues/327
