### ISSUE TITLE
BYG Wooden Logs Unable to Craft Into Planks When Polymorph is Installed (Forge 1.16.1)

### ISSUE THREAD

**Issue by steelfoot** [TheIllusiveC4/Polymorph#17]
#### Versions:
* Polymorph: 0.11
* Oh the Biomes You'll Go 1.0.12
* Forge/Fabric: Forge 32.0.75
#### Steps to Reproduce:
1. Get log from BYG
2. Attempt to craft log from BYG
3. Fail to craft log from BYG

Crash Log: n/a

NOTES:  This bug was not present in Polymorph 0.10.

**Comment by TheIllusiveC4** [comment]
Works for me.

![2020-07-25_19 19 03](https://user-images.githubusercontent.com/29991504/88469963-c222a000-ceab-11ea-8e57-7784a57172aa.png)

Are these the only mods present when you tested this?

**Comment by steelfoot** [comment]
They were, but I found that that wasn't the issue after installing FastWorkbench and discovering the same issue.  Reinstalling Java seems to have solved the problem.

Note to self:  check that first.
