### ISSUE TITLE
Smokers Don't seem to add the GUI button

### ISSUE THREAD

**Issue by Zunwolf1896** [TheIllusiveC4/Polymorph#171]
#### Versions (Be specific, do not write "latest"):
* Polymorph: 0.0.20-1.18.2
* Fabric: 0.13.3
* Food+: 1.4.0
* Croptopia: 2.0.1
#### Steps to Reproduce:
1. Have the mentioned rods installed. 
2. Put sugar into a smoker and smelt. 
3. The sugar will become the Croptopia Caramel, not allowing you to use the Food+ caramel recipes. 
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by TheIllusiveC4** [comment]
I cannot reproduce this bug, using these mods and placing sugar into a Smoker pops the GUI up just fine. 

Did you reproduce this with ONLY these mods installed?
