### ISSUE TITLE
Conflict with AE2

### ISSUE THREAD

**Issue by LyceenAiro** [TheIllusiveC4/Polymorph#172]
Versions :Minecraft 1.18.2
* Polymorph:polymorph-forge-1.18.2-0.44.jar
* Forge:forge-40.1.19
* conflicting mods:appliedenergistics2-11.0.0-alpha.6.jar

 Steps to Reproduce:
1.install Minecraft-1.18.2-Forge-40.1.19
2.add mods polymorph-forge-1.18.2-0.44.jar
3.add mods appliedenergistics2-11.0.0-alpha.6.jar
4.start the game
5.show bug report

Crash Log: https://paste.ubuntu.com/p/BKPWVpKSx2/

**Comment by TheIllusiveC4** [comment]
You have to update your AE2 version to 11.0.0+ (release, not alpha).
