### ISSUE TITLE
The problem happen again, no button on furnace, I have 1 egg can be fried in 3 different fried egg but no button to choose. crafting table still work

### ISSUE THREAD

**Issue by ardissaps** [TheIllusiveC4/Polymorph#175]
MC 1.18.2

Mod all latest version :
Polymorp
Additional Addition
Farmer Delight
Better Animal Plus

Put Egg on the Furnace, no button. All crafted to Additional Addition only..
Crafting Table works fine for copper sword

**Comment by TheIllusiveC4** [comment]
I can't reproduce this, using only those four mods I am able to switch between all three fried egg types. Are you using ONLY those four mods? If not, you will need to find the mod that is causing this conflict.

**Comment by ardissaps** [comment]
> I can't reproduce this, using only those four mods I am able to switch between all three fried egg types. Are you using ONLY those four mods? If not, you will need to find the mod that is causing this conflict.

I am using autotag from modrinth, could possibly cause issue?

**Comment by TheIllusiveC4** [comment]
I don't know, possibly? You'd have to take out the mod and test it. Is that the only other mod that you have?

**Comment by ardissaps** [comment]
> I don't know, possibly? You'd have to take out the mod and test it. Is that the only other mod that you have?

I actually use a lot of mods :
![sdasdadasdad](https://user-images.githubusercontent.com/82106625/173463416-8d44539f-2f6e-45af-835b-c94c3d532147.jpg)

**Comment by TheIllusiveC4** [comment]
That's what I was referring to earlier, if you have more mods than just the ones you listed then any one of them could be causing this issue. You need to:

1. Remove all those mods except for the four that you listed and then test to see if it's still an issue.
2. If it's still an issue with just those four mods, report back with those results.
3. If it's NOT still an issue with just those four mods, you need to identify which mod in your modlist is causing the issue. This can be done more efficiently by doing a binary search where you add back in only half of the mods, check for the issue, and then keep trimming the list down by half until you find the cause.

I can't do much more to resolve the issue until you can identify the source of the issue.

**Comment by ardissaps** [comment]
Ok I'll try remove some mods/tweak that could possibly edit furnace and try again. I'll post again if I found it, thank you for your time!
