### ISSUE TITLE
Missing Furnace/Smoker Button

### ISSUE THREAD

**Issue by andi-makes** [TheIllusiveC4/Polymorph#178]
#### Versions (Be specific, do not write "latest"):

Base Mods:
* Polymorph: 0.0.21-1.18.2
* Fabric Loader: 0.14.8
* Fabric API: 0.58.0+1.18.2
* Additional Additions: 4.0.5
* Farmer's Delight: 1.18.2-0.2.1

Problem Mods:
* Botania: 1.18.2-434-FABRIC, dependent on:
    * Trinkets: 3.3.1
    * Patchouli: 1.18.2-71.1-FABRIC
* Alloy Forgery: 2.0.13+1.18, dependent on:
    * owo-lib: 0.7.2-no-cme+1.18
* Expanded Storage: 7.4.0-beta.4, dependent on:
    * Ellemes' Container Library: 1.4.0-beta.2

#### Observed Behavior:
No "Change Output" button in the furnace.
#### Expected Behavior:
A "Change Output" button in the furnace. (Like with just the "Base Mods" installed)
#### Steps to Reproduce:
1. Install the "Base Mods"
2. Install one of the "Problem Mods"
3. Put Eggs in a Furnace/Smoker

The dependencies of the "Problem Mods" don't seem to be the issue, the button exists with just the dependencies installed.

This issue is related to #158 and is probably somehow also related to #175 (even though none of the "Problem Mods" I tested are in their instance) and maybe also #171, as they show the same symptoms.

**Comment by TheIllusiveC4** [comment]
Just to be clear, you're saying this problem happens if any ONE of the problem mods are installed correct?

**Comment by andi-makes** [comment]
Correct!

**Comment by Shadowrs** [comment]
My furnace button is also missing. I'm on a custom "another quality modpack" pack with 200+ mods, doing /polymorph conflicts doesnt seem to do anything (no log file or latest.log output). testing 200 mods 1by1 is unfeasible, any suggestions for investigating?

**Comment by andi-makes** [comment]
I did the following:

Firstly, I only enabled the "Base Mods". The Furnace Button shows, so this is my baseline for further testing.

Then, I took a batch of mods (like, 10-20) and enabled them. Launched Minecraft, tested whether the furnace button showed - If it did, then those mods are compatible, if it didn't, I disabled half of the newly enabled mods, tried it again, and basically did a "binary search" until one mod remained.
Because there are seemingly multiple mods causing this issue, I enabled all mods of the batch again without the one mod that causes the issue, and if the issue still exists, there is another mod causing the issue in that batch.

After working through the batch, test the next 10-20 mods and carry on until you've tested all mods.

<details>
<summary>Here is a list of mods that work on my instance, you can maybe skip validating those:</summary>

 - `3dskinlayers-fabric-1.4.6-mc1.18.2.jar`
 - `AdditionalAdditions-4.0.5.jar`
 - `Adorn-3.5.0+1.18.2-fabric.jar`
 - `advancednetherite-fabric-1.5.1-1.18.2.jar`
 - `another_furniture-fabric-1.1.1-1.18.2.jar`
 - `AnvilFix-1.3.0.jar`
 - `appleskin-fabric-mc1.18.2-2.4.0.jar`
 - `architectury-4.6.77-fabric.jar`
 - `authme-mc1.18.2-3.1.0.jar`
 - `badpackets-fabric-0.1.2.jar`
 - `baguette-1.1.3+1.18.2.jar`
 - `betterbiomeblend-1.18.2-1.3.5-fabric.jar`
 - `BetterF3-1.2.5-Fabric-1.18.2.jar`
 - `BetterPingDisplay-Fabric-1.18.2-1.1.1.jar`
 - `bewitchment-1.18-23.jar`
 - `bewitchmentplus-1.18.2-17.jar`
 - `biomemakeover-FABRIC-1.18.2-1.4.29.jar`
 - `bitsandchisels-2.6.13.jar`
 - `blossom-fabric-1.18.2-1.0.5.jar`
 - `bodaciousberries-1.5.0+mc1.18.2.jar`
 - `Bookshelf-Fabric-1.18.2-13.2.47.jar`
 - `brb-Forge-1.5.6.jar`
 - `BuildingWands_mc1.18.2-2.6_beta-fabric.jar`
 - `c2me-fabric-mc1.18.2-0.2.0+alpha.7.0-all.jar`
 - `cammies-minecart-tweaks-1.5.jar`
 - `campanion-3.0.4.jar`
 - `Capes-1.3.1+1.18.2.jar`
 - `cardinal-components-api-4.2.0.jar`
 - `cardinal-components-base-4.2.0.jar`
 - `cardinal-components-entity-4.2.0.jar`
 - `cardinal-components-item-4.2.0.jar`
 - `carrier-1.10.0.jar`
 - `cc-prometheus-fabric-1.18.2-2.0.1.jar`
 - `cc-restitched-1.100.8.jar`
 - `chalk-2.0.0+1.18.2.jar`
 - `charm-fabric-1.18.2-4.1.2.jar`
 - `charmingrequiem-1.0.0.jar`
 - `charmonium-fabric-1.18.2-4.1.0.jar`
 - `chime-1.2.1.jar`
 - `chocolatebar-v0.1.4+mc1.18.2.jar`
 - `Chunky-1.2.164.jar`
 - `cloth-config-fabric-6.2.62.jar`
 - `conjuring-1.0.22+1.18.jar`
 - `connectiblechains-2.1.1+1.18.2.jar`
 - `consistency_plus-0.5.0+1.18.2-fabric.jar`
 - `continuity-2.0.0+1.18.2.jar`
 - `CopperStuff-1.18.2-1.0.0.1913186568.jar`
 - `create-mc1.18.2_v0.5.0+691.jar`
 - `createplus-1.0.0-beta4.jar`
 - `creeper-spores-1.8.0.jar`
 - `crops_love_rain-1.2.2.jar`
 - `Croptopia-1.18.2-FABRIC-2.0.5.jar`
 - `culinaire-2.4.0.jar`
 - `CullLessLeaves-1.0.1.jar`
 - `dark-enchanting-1.0.0+1.18.2.jar`
 - `darkrites-1.18.2-1.jar`
 - `dawn-3.3.2.jar`
 - `Decorative Blocks-fabric-1.18.2-2.1.0.jar`
 - `deepmoblearning-refabricated-0.5.6-BETA+1.18.2.jar`
 - `DistantHorizons-1.6.5a-1.18.2.jar`
 - `DyeableFishingLines-Fabric-1.0.0.jar`
 - `dynamic-fps-2.1.0.jar`
 - `ears-fabric-1.17-1.4.5_01.jar`
 - `eating-animation-1.8.jar`
 - `emotecraft-for-MC1.18.2-2.1.3-SNAPSHOT-build.32-fabric.jar`
 - `EnchantmentDescriptions-Fabric-1.18.2-10.0.6.jar`
 - `enhancedblockentities-0.7.1+1.18.2.jar`
 - `entityculling-fabric-mc1.18-1.5.1.jar`
 - `expandeddelight-0.1.8.1.jar`
 - `extraalchemy-fabric-1.18.2-1.8.1.jar`
 - `extremesoundmuffler-3.28_fabric-1.18.2.jar`
 - `fabric-api-0.58.0+1.18.2.jar`
 - `fabric-language-kotlin-1.8.2+kotlin.1.7.10.jar`
 - `farmers-delight-fabric-1.18.2-0.2.1.jar`
 - `feature_nbt_deadlock_be_gone_fabric-2.0.0+1.18.2-rc1.jar`
 - `ferritecore-4.2.1-fabric.jar`
 - `fireworkfrenzy-1.8.jar`
 - `fish_of_thieves-mc1.18.2-v1.0.7-fabric.jar`
 - `ftb-chunks-fabric-1802.3.6-build.147.jar`
 - `ftb-library-fabric-1802.3.6-build.123.jar`
 - `ftb-teams-fabric-1802.2.6-build.51.jar`
 - `geckolib-fabric-1.18-3.0.51.jar`
 - `GravityChanger-0.7.10-1.18.2.jar`
 - `grizzlybear-1.18-1.3.jar`
 - `haema-1.10.1+1.18.2.jar`
 - `half-doors-1.18.2-fabric-1.3.7.jar`
 - `hatlist-1.2.jar`
 - `here-be-no-dragons-1.0.0.jar`
 - `hexcasting-fabric-1.18.2-0.9.0.jar`
 - `horseinboat-fabric-1.1.2.jar`
 - `IKnowWhatImDoing-4.1.0-fabric.jar`
 - `indium-1.0.6+mc1.18.2.jar`
 - `inmis-2.6.0-1.18.2.jar`
 - `iris-mc1.18.2-1.2.6.jar`
 - `jam-lib-0.0.5.jar`
 - `jamtastic-1.4.6.jar`
 - `kentucky-fried-axolotls-1.0.1-1.18.2.jar`
 - `kiln-1.2.0+1.18.2.jar`
 - `lambdabettergrass-1.2.4+1.18.jar`
 - `lambdynamiclights-2.1.0+1.17.jar`
 - `lanterns-belong-on-walls-1.3.0-1.18.x.jar`
 - `lazydfu-0.1.2.jar`
 - `leaves-us-in-peace-1.0.5+MC1.18-1.18.2.jar`
 - `letsjeb-1.0.0.jar`
 - `light-overlay-6.1.0-fabric.jar`
 - `lithium-fabric-mc1.18.2-0.7.10.jar`
 - `lootr-1.18.2-0.3.23.60.jar`
 - `lovely_snails-1.0.4+1.18.jar`
 - `lunade-copper-pipe-1.11b-1.18.2b.jar`
 - `mavm-mc1.19-fabric-1.0.8a.jar`
 - `mcemojis-1.5.1.jar`
 - `mealapi-0.3.1+1.18.2.jar`
 - `modmenu-3.2.3.jar`
 - `moremusic-0.1.3+1.18.2.jar`
 - `mostructures-1.4.2+1.18.2.jar`
 - `mousewheelie-1.10.2+mc1.18.2.jar`
 - `mythic-mounts-1.18.2-7.0.jar`
 - `NaturesCompass-1.18.2-2.0.3-fabric.jar`
 - `nears-fabric-1.18-1.1.8.jar`
 - `nethermap-2.0.2-1.18.2.jar`
 - `notenoughanimations-fabric-1.6.0-mc1.18.2.jar`
 - `notenoughcrashes-4.1.6+1.18.2-fabric.jar`
 - `OpenLoader-Fabric-1.18.2-12.0.1.jar`
 - `overweightfarming-1.18.2-1.5.3-fabric.jar`
 - `owo-lib-0.7.2+1.18.jar`
 - `paradise-lost-1.6.9+1.18.2.jar`
 - `Patchouli-1.18.2-71.1-FABRIC.jar`
 - `paucal-fabric-1.18.2-0.4.7.jar`
 - `Pehkui-3.3.3+1.14.4-1.19.1.jar`
 - `pettablebees-fabric-1.1.0.jar`
 - `phonos-0.3+1.18.2.jar`
 - `plantinajar-2.3.1.jar`
 - `plated-2.2.0.jar`
 - `pling-1.5.0.jar`
 - `plushie-mod-1.2-1.18.2.jar`
 - `polymorph-fabric-0.0.21-1.18.2.jar`
 - `Powah-3.0.2-beta.jar`
 - `promenade-2.6.3.jar`
 - `purpeille-2.3.3+fabric-1.18.2.jar`
 - `quilt-loading-screen-2.2.0+1.17.jar`
 - `Randore-fabric-2.0.1-mc1.18.2.jar`
 - `reeses_sodium_options-1.4.4+mc1.18.2-build.46.jar`
 - `repurposed_structures_fabric-4.1.14+1.18.2.jar`
 - `requiem-2.0.0-beta.9.jar`
 - `rightclickharvest-2.2.1+1.18.jar`
 - `rocks-1.6.0.jar`
 - `RoughlyEnoughItems-8.3.519.jar`
 - `sandwichable-1.3+1.18.2.jar`
 - `screenshotcopy-1.1.0-fabric.jar`
 - `shadowedactionbar-1.0.0.jar`
 - `simulacrum-0.5.4-beta.jar`
 - `sodium-extra-0.4.6+mc1.18.2-build.46.jar`
 - `sodium-fabric-mc1.18.2-0.4.1+build.15.jar`
 - `spark-1.9.11-fabric.jar`
 - `spectrum-1.4.2-1.18.2-chaos_and_exploration.jar`
 - `spyglass-improvements-1.2+mc1.18.2+fabric.jar`
 - `starlight-1.0.2+fabric.89b8d9f.jar`
 - `statuseffecttimer-1.1.1+1.18.1.jar`
 - `stoneholm-1.4.3.jar`
 - `stormfest-1.0.3.jar`
 - `teenycoal-1.1.3-1.16.x-1.17.x-1.18.x-1.19-snapshot.jar`
 - `TerraBlender-fabric-1.18.2-1.1.0.102.jar`
 - `Terralith_v2.2.1a.jar`
 - `textile_backup-2.4.0-1.18.jar`
 - `the_bumblezone_fabric-5.1.2+1.18.2.jar`
 - `toms_storage_fabric-1.18.2-1.3.4.jar`
 - `traverse-5.1.0.jar`
 - `trinkets-3.3.1.jar`
 - `turtle-soup-1.0.2.jar`
 - `twilightforest-fabric-1.18.2-4.1.251.jar`
 - `universal_ores-1.3.1.jar`
 - `vanilla-claws-1.0.0.jar`
 - `vanillaexcavators-2.3.1-1.18.2.jar`
 - `vanilla-hammers-3.4.0-1.18.2.jar`
 - `visuality-0.4.2.jar`
 - `windchimes-1.2.0.jar`
 - `wired-redstone-0.3.6+1.18.2.jar`
 - `wolves-with-armor-1.7.1-1.18.2.jar`
 - `wthit-fabric-4.11.0.jar`
 - `wthit-plugins-1.0.6+1.18.2.jar`
 - `xp_obelisk-0.4.2.r_for_1.18.x_Fabric.jar`
 - `youre-in-grave-danger-1.3.7.jar`
</details>

**Comment by TheGrimsey** [comment]
Encountered this issue as well, and in my case, it appears to be related to ``Botania``.

With **just** the following mods removing Botania fixes the issue:
- Fabric Loader 0.14.8
- Fabric API 0.58.0+1.18.2
- Botania-1.18.2-434-FABRIC
    - Patchouli-1.18.2-71.1-FABRIC
    - trinkets-3.3.1
- TechReborn-5.2.0
    - RebornCore-5.2.0
- BeyondEarth-1.0.1
    - cloth-config-6.2.62-fabric

**Comment by Khaeops** [comment]
Also having this issue when trying to cook eggs into any of various mods' Fried Eggs recipes, it always picks the first one available in JEI. I have Botania installed. Mods I have with Fried Eggs are:

- Incubation
- Farmer's Delight
- Better Animals Plus
- MoreFoods Mod by Daleeny
- Sandwich Mod.

**Comment by otavio-silva** [comment]
I'm having the same problem, I have 4~5 egg variants and it always outputs the same one, the button is not there. Anything that processes stuff in a furnace-like interface, the button is gone.

**Comment by PhweeDev** [comment]
This also happens on Forge too, granted this is a Fabric issue, I thought I'd mention that it also occurs on Forge 1.18 too

**Comment by otavio-silva** [comment]
Any news on this?
Still the furnace button is not showing, and that would be really nice...

**Comment by Traehgniw** [comment]
I'm playing the modpack You Like Food, which doesn't have Botania. It's a Forge 1.18.2 modpack where the goal is to make all the food items. There are a lot of mushroom-related recipe conflicts and it's an Issue.
