### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by AngelTiramisu** [TheIllusiveC4/Polymorph#180]
#### Versions (Be specific, do not write "latest"):
* Polymorph: 1.18.2
* Forge/Fabric: forge
#### Steps to Reproduce:
1.
2.
3.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

all i have is this line 
stop
eventjava.lang.OutOfMemoryError: unable to create
native thread: possibly out of memory or
process/resource limits reached

**Comment by TheIllusiveC4** [comment]
There has to be more to the logs that you can share, otherwise how do you know it's a Polymorph issue? Nothing in those few lines point to this mod.

**Comment by AngelTiramisu** [comment]
For some reason the crashes never created a log i can share but i spoke to support  on the site i use and this was the newest mod we added and they told me to remove it because it was causing a memory leak and as soon as it was removed everything went back to normal

**Comment by AngelTiramisu** [comment]
![A36EDB81-3DE5-43F1-A943-84CA2DD515F7](https://user-images.githubusercontent.com/28626706/185820235-ec53c8fa-19eb-47bf-8eac-6639a54b84d5.png)


This was all i could get since it didnt create a log

**Comment by TheIllusiveC4** [comment]
Okay it might not create a crash log, but there are the regular logs too. Please share either the `latest.log` or `debug.log` file in your `logs` folder right after the crash happens.
