### ISSUE TITLE
[1.16.5 (and likely others going up)] Issues with fastsuite and the button not appearing.

### ISSUE THREAD

**Issue by Darkmega18** [TheIllusiveC4/Polymorph#182]
#### Versions (Be specific, do not write "latest"):
* Polymorph: polymorph-forge-1.16.5-0.40.jar
* Forge/Fabric: 1.16.5 - 36.2.39
* FastSuite: FastSuite-1.16.4-1.1.1.jar

#### Observed Behavior:
When both fastsuite and polymorph are installed the polymorph button fails to appear inside viable guis, like furnaces and work benches.

#### Expected Behavior: 
Both should be capable of working together, for large modpack recipe changing _(4 types of fried egg in the furnace moment. :V)_ and faster recipe access as fastsuite is meant to give.

#### Steps to Reproduce:
1. Install FastSuite for Shadows_of_fire.
2. Install Polymorph.
3. Install some some mods that have recipe overlaps, Such as atum and it's glass being forge dictionaried and so not smelting to their own glass without being toggled. Various food mods that try to add fried eggs, several mods with similar metal armors (mystical world and ice and fire comes to mind for copper etc.)
4. Notice that the gui icon is gone when it's meant to be applicable.
...

Crash Log: There is none. it's just an ongoing bug.

**Comment by Darkmega18** [comment]
Noice.

**Comment by P3rf3ctXZer0** [comment]
This is still an issue for 1.19.2
