### ISSUE TITLE
[1.16.1] Button isn't correctly placed on refined storage crafting grid

### ISSUE THREAD

**Issue by WhitePhant0m** [TheIllusiveC4/Polymorph#19]
#### Versions (Be specific, do not write "latest"):
* Polymorph: 0.11
* Forge/Fabric: 32.0.88
#### Observed Behavior:
The button seems to not move when you change the size of the crafting grid
![image](https://user-images.githubusercontent.com/33400200/89117382-01ea1880-d4a6-11ea-9b83-7b0796146119.png)
![image](https://user-images.githubusercontent.com/33400200/89117388-0d3d4400-d4a6-11ea-91ab-5b0bd9b31b10.png)
And even on small the recipe select is hiding behind the items
![image](https://user-images.githubusercontent.com/33400200/89117406-35c53e00-d4a6-11ea-9134-6ea7cdb05d50.png)
#### Expected Behavior:
For the button to move to proper spots when changing size of the grid and for recipes to be above the items

**Comment by TheIllusiveC4** [comment]
Oh, I didn't realize that you could change the size. Very interesting. Hopefully this is an easy fix.
