### ISSUE TITLE
Minecraft 22w43a unable to craft by right click

### ISSUE THREAD

**Issue by ghost** [TheIllusiveC4/Polymorph#193]
#### Versions (Be specific, do not write "latest"):
* Minecraft: 22w43a and beyond
* Polymorph: 0.45.0
* Forge/Fabric: Fabric
#### Steps to Reproduce:
1. Install 22w43a snapshot
2. Pick-up some blocks in creative
3. Use right click in crafting table

Crash Log: https://pastebin.com/83M40TFc

#### Additional information:
```json
{
    "type": "crafting_shapeless",
    "ingredients": [{ "item": "minecraft:barrier" }],
    "result": { "item": "minecraft:barrier", "count": 1 }
}
```

**Comment by TheIllusiveC4** [comment]
This could just be an error related to the snapshot itself, but I don't update to snapshot versions so please wait for the official 1.19.3 release for this to be fixed (if still necessary).

**Comment by unit-a-user** [comment]
I forgot to add: 
```json
{
    "type": "crafting_shapeless",
    "ingredients": [{ "item": "minecraft:barrier" }],
    "result": { "item": "minecraft:barrier", "count": 1 }
}
```
Problem have when multiple.

**Comment by ghost** [comment]
Probably, we needs really waiting official 1.19.3 release or beta, nor alpha.

**Comment by TheIllusiveC4** [comment]
You're free to fork and build your own version, the mod is open source. But I wouldn't accept any PRs to update to snapshots. My decision to not update to snapshot versions is not due to lack of time, it's due to the fact that I don't want to release versions for snapshots that are very susceptible to change in subsequent releases. For me, I'd rather wait until the official release before updating.

**Comment by unit-a-user** [comment]
Okay, I'll try to keep you posted on changes like that. I will update once a week, snapshot by snapshot, and only when I can afford it.

**Comment by unit-a-user** [comment]
Alas, it is unlikely that this mod may not survive further snapshots. Mapping might not work at all in the near future.

**Comment by unit-a-user** [comment]
Test port still working on 22w44a.
