### ISSUE TITLE
Add to Modrinth

### ISSUE THREAD

**Issue by sylv256** [TheIllusiveC4/Polymorph#199]
**Please describe the new feature or change.**
Please add this mod to Modrinth to make it easier for modpack creators etc. on Modrinth.

**Please describe why you want this feature.**
An increasing number of mods are moving to Modrinth, especially as they recently added monetization support. Modrinth is a platform with better searching, API, and features for mod developers, and their community and developers are very welcoming to developers.

**Comment by TheIllusiveC4** [comment]
https://modrinth.com/mod/polymorph
