### ISSUE TITLE
Weird Error in Logs (Doesn't cause any problem)

### ISSUE THREAD

**Issue by Camawama** [TheIllusiveC4/Polymorph#20]
Very simple report here. I am on the latest version of Forge and the Latest version of the Mod and when starting up Minecraft, in the Logs I find this error. I tested every single mod in my modpack and it only showed up with your mod. Hopefully, it can fix an issue later down the line :)

![weird error](https://user-images.githubusercontent.com/43620900/89141324-eadd1200-d509-11ea-8437-2e4e04294e5f.png)

**Comment by TheIllusiveC4** [comment]
This isn't an issue, so don't worry about it. And it'll likely disappear in the 1.16.2 version.
