### ISSUE TITLE
1.19.3 - Release please.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TheIllusiveC4/Polymorph#204]
**Please describe the new feature or change.**

I just want to be able to use this mod on 1.19.3

**Please describe why you want this feature.**

Cause mods have started migrating to 1.19.3

**Comment by gamerpotion** [comment]
Awaiting a 1.19.3 also.

**Comment by Rogenar** [comment]
There are mods where I have some recipe conflicts, will this mod fix the issues? I'm also waiting for version 1.19.3.

**Comment by GoldenFurredFox** [comment]
Don't wanna create a duplicate issue, but just want to confirm that absolutely no recipe tweaker mods exist for 1.19.3. Some jumped straight from .2 to .4 and others simply haven't passed .2, so I'm trying to gather a list of crafttweaker alternative mods so I can call their mod devs to action and see if they'll make versions for 1.19.3.

Please, C4, **please** make a 1.19.3 update. We need it now more than ever.

A similar post for CraftTweaker exists at [https://github.com/CraftTweaker/CraftTweaker/issues/1642](url). Please go give it some love.

**Comment by TheIllusiveC4** [comment]
Released for 1.19.3.
