### ISSUE TITLE
Crash whilst initializing game

### ISSUE THREAD

**Issue by HoottooH** [TheIllusiveC4/Polymorph#208]
#### Versions (Be specific, do not write "latest"):
* Polymorph: **0.46.1**
* Forge/Fabric: **43.2.6 (1.19.2)**
Observed Behavior: **Launcher doesn't make it past the initialization phase**
Expected Behavior: **Proper initialization** 
Steps to Reproduce: **While it's possible for you to download every single one of the 103 mods needed to reproduce this, this isn't a fabric mod and the issue is probably just between 1 or 2 other mods so I personally don't recommend the attempt, but the hastebin has every mod in the pack listed in their running or disabled states.** 

1. Launch game
2. Hit play button
3. Wait until game crashes and returns with the report of:
```
The game crashed whilst initializing game
Error: java.lang.RuntimeException: null

```

Crash Log: 
[https://hastebin.com/share/omiwasezoh.perl](https://hastebin.com/share/omiwasezoh.perl)

If you want to try to reproduce, lmk and I will gladly link you to a mega folder with all the files!

**Comment by TheIllusiveC4** [comment]
Sorry for the delay in response, though it seems the log has expired now so I cannot reference the error anymore.

I haven't received any other reports of an immediate launcher crash so I have to assume this is either a very particular set of mods with Polymorph or this is just another mod causing it entirely. I'm closing this as stale as it's been a while and many things may have changed, but feel free to comment with a new log if this is still an issue and I'll re-open it.
