### ISSUE TITLE
Polymorph button not appearing for crafting table in Catserver 1.16.5

### ISSUE THREAD

**Issue by FZonner** [TheIllusiveC4/Polymorph#215]
#### Versions (Be specific, do not write "latest"):
* Polymorph: 1.16.5-0.41
* Forge/Fabric: Forge 36.2.39 
#### Observed Behavior:
The button does not appear on my server, I use catserver 1.16.5 latest version available.
#### Expected Behavior:
The botton appears normally in an offline world, the server configuration is by default except in online mode where I have it set to "false".
**The puglins I have only are:**
EssentialsX 2.19.7
EssentialsX Chat 2.19.7
EssentialsX Spawn 2.19.7
LoginSecurity-3.1.1-Spigot
**And these are mods that are only on the server side:**
AI-Improvements-1.16.5-0.5.0
dusk-1.4
EverlastingSkins-1.16.5-0.3.0.3
limitedchunks-2.1
smoothchunk1.16.5-2.0

**Comment by TheIllusiveC4** [comment]
I'm not sure what might be causing the issue, but I do not support hybrid servers like CatServer. If there is an issue that does not exist outside of the server, then it is likely an issue with either CatServer or an interaction between a mod and a plugin and I cannot address either of those situations unfortunately.
