### ISSUE TITLE
Not working for 1.16.5 

### ISSUE THREAD

**Issue by Danyko03** [TheIllusiveC4/Polymorph#217]
#### Versions (Be specific, do not write "latest"): 1.16.5
* Polymorph: 1.16.5-0.41
* Forge/Fabric:Forge
#### Steps to Reproduce:
1. Downloaded file
2. Put the file in the mod folder
3. Opened minecraft
4. Opened my world
5. Since the mod was not working I decided to check the mod list in game
6. Forge was not even noticing the mod so I tried to download the file again, it doesn't worked 
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by TheIllusiveC4** [comment]
What is the name of the JAR file exactly, and where did you download it from?
