### ISSUE TITLE
Error FastWorkbench and Crafting Station

### ISSUE THREAD

**Issue by ArturilloD** [TheIllusiveC4/Polymorph#22]
#### Versions (Be specific, do not write "latest"):
* Polymorph: 1.15.2-0.9
* Forge/Fabric: forge 31.2.36
#### Observed Behavior: There is incompatibility between FastWorkbench and Crafting Station, when having both installed the button does not appear.

Also I wanted to add that I think it would be great if you could add compatility with Inventory Crafting Grid: https://www.curseforge.com/minecraft/mc-mods/inventory-crafting-grid

#### Steps to Reproduce:
1.
2.
3.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by TheIllusiveC4** [comment]
Sorry I can't reproduce this. Everything works fine for me with both those mods installed. Did you test this with only those mods installed and nothing else?

**Comment by ArturilloD** [comment]
I have removed a few mods, since it was impossible to play and for now it does not seem to be happening again. I suppose there is incompatibility with some of them.
