### ISSUE TITLE
CRASH WHEN START IDK WHY

### ISSUE THREAD

**Issue by xparadise95** [TheIllusiveC4/Polymorph#220]
#### Versions (Be specific, do not write "latest"):
* Polymorph: 0.46.1+1.19.2

* Forge/Fabric: Fabric 1.19.2
#### Steps to Reproduce:
1.
2.
3.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
https://pastebin.com/spZVfAEH

**Comment by TheIllusiveC4** [comment]
This seems like either a BetterFPS, Cardinal Components, or Optifine issue. Please first try without Optifine/Optifabric, as it often causes issues with other mods. If it still crashes, try updating to the latest BetterFPS and/or Cardinal Components. Either way, this does not seem to indicate a Polymorph issue.
