### ISSUE TITLE
[Suggestion] Add a way to morph already smelted/crafted items

### ISSUE THREAD

**Issue by Catomax262** [TheIllusiveC4/Polymorph#221]
**Please describe the new feature or change.**
Idk, like, a new transmutator station or something

**Please describe why you want this feature.**
I accidentally crafted a lead ingot which does nothing compared to its working brother. I'd like the same thing as morphing items before they get crafter, but for already crafted items (for example i have lots of iron dust from different mods, how can i merge them without having to smelt it into ingots first?)

**Comment by TheIllusiveC4** [comment]
This would be outside the scope of the mod.

**Comment by Catomax262** [comment]
> This would be outside the scope of the mod.

Maybe not a station, but a function?
