### ISSUE TITLE
Missing polymorph button[Bug]: 

### ISSUE THREAD

**Issue by MrTangoPIG** [TheIllusiveC4/Polymorph#227]
### Minecraft Version

1.19.2

### What happened?

I dont get the polymorph button show up in any menu.

### How do you trigger this bug?

Its going to be a conflict with my modlist, but no clue which.

Generated via curseforge:
Flywheel (by jozufozu)
Dusk[Forge/Fabric] (by someaddon)
Just Enough Items (JEI) (by mezz)
CorgiLib (by Corgi_Taco)
Terralith (by Starmute)
Create Confectionery (by Furti_Two)
Better Animations Collection (by Fuzs)
Easy Shulker Boxes (by Fuzs)
Visual Workbench [Forge & Fabric] (by Fuzs)
HT's TreeChop (by hammertater)
Drip Sounds (Forge) (by PieKing1215)
Spice of Life: Apple Pie Edition (by Anthxny)
Elytra Slot (Fabric/Forge/Quilt) (by TheIllusiveC4)
SwingThroughGrass (by exidex)
Cloth Config API (Fabric/Forge) (by shedaniel)
Double Doors (by Serilum)
Wool Tweaks (by Serilum)
Easy Magic [Forge & Fabric] (by Fuzs)
Auto Ore Dictionary Converter (by MattDahEpic)
Charm of Undying (Fabric/Forge/Quilt) (by TheIllusiveC4)
Supplementaries (by MehVahdJukaar)
Iris & Oculus Flywheel Compat (by leon_mout)
Curios API (Forge) (by TheIllusiveC4)
Compat O' Plenty (by tdstress)
Moonlight Lib (by MehVahdJukaar)
Leaves Be Gone (by Fuzs)
Stoneworks [Forge & Fabric] (by Fuzs)
Responsive Shields (by Revvilo)
Mysterious Mountain Lib (by sz0999312)
MattDahEpic Core (MDECore) (by MattDahEpic)
AmbientSounds 5 (by CreativeMD)
Better Tridents (by Fuzs)
Ecologics (by SameDifferent)
Smarter Farmers (farmers replant) (by MehVahdJukaar)
Macaw's Trapdoors (by sketch_macaw)
Ocean's Delight (by scouter567)
Easy Anvils [Forge & Fabric] (by Fuzs)
Spiky Spikes (by Fuzs)
Just Enough Resources (JER) (by way2muchnoise)
Rubidium (by Asek3)
Macaw's Doors (by sketch_macaw)
Clumps (by Jaredlll08)
Wooden Bucket (by thecech12)
Storage Labels (by MehVahdJukaar)
Towns and Towers (by Biban_Auriu)
Caelus API (Forge) (by TheIllusiveC4)
SuperMartijn642's Config Lib (by SuperMartijn642)
Citadel (by sbom_xela)
Immersive Weathering [FORGE] (by OrdanaryMods)
Kiwi 🥝 (Forge) (by Snownee_)
Create (by simibubi)
Blueprint (by TeamAbnormals)
AutoRegLib (by Vazkii)
Corn Delight (by sz0999312)
Leave My Bars Alone (by Fuzs)
SuperMartijn642's Core Lib (by SuperMartijn642)
Universal Bone Meal [Forge & Fabric] (by Fuzs)
Alex's Mobs (by sbom_xela)
Vertical Slabs Compat (by MehVahdJukaar)
Diet (Fabric/Forge/Quilt) (by TheIllusiveC4)
Sophisticated Core (by P3pp3rF1y)
Puzzles Lib [Forge & Fabric] (by Fuzs)
Farmer's Compats (by nocubeyt)
Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)
Alex's Delight (by NCP_Bails)
Create: Steam 'n' Rails (by mattentosh)
Enhanced Celestials - Blood, Blue, & Harvest (Super) Moons (by Corgi_Taco)
Oculus (by Asek3)
Biomes O' Plenty (by Forstride)
Polymorph (Fabric/Forge/Quilt) (by TheIllusiveC4)
Magnesium/Rubidium Extras (by Anthxny)
Guard Villagers (by almightytallestred)
Croptopia (by thethonk)
Fisherman's Trap (by TooManyKitKats)
Architectury API (Fabric/Forge) (by shedaniel)
GeckoLib (by Gecko)
Carry On (by Tschipp)
[Let's Do] Vinery (by satisfy)
Ender's Delight (by Furti_Two)
Small Ships [Fabric & Forge] (by talhanation)
Dungeons and Taverns (by Nova_Wostra)
[Let's Do] API (by Cristelknight)
Horse Expert (by Fuzs)
Magnesium/Rubidium Dynamic Lights (by Anthxny)
AppleSkin (by squeek502)
Hearth & Home (by Starfish_Studios)
Snow! Real Magic! ⛄ (Forge) (by Snownee_)
TerraBlender (Forge) (by TheAdubbz)
Italian Delight (A Farmer's Delight Add-on) (by PuurpZ)
Structory (by botanydev)
Effective (Forge) (by BottomTextDanny)
Another Furniture (by Starfish_Studios)
Quark (by Vazkii)
Farmer's Respite (by lumpazl)
Dynamic Surroundings Resurrected (by theNyfaria)
CreativeCore (by CreativeMD)
Chunk Loaders (by SuperMartijn642)
Nether's Delight (by lumpazl)
BucketLib (by thecech12)
Every Compat (Wood Good) (by MehVahdJukaar)
Universal Enchants (by Fuzs)
Collective (by Serilum)
Sophisticated Backpacks (by P3pp3rF1y)
Miner's Delight + (by soytutta)
Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)
Sound Physics Remastered (by henkelmax)
Farmer's Delight (by vectorwing)
Nyf's Spiders (by theNyfaria)
Oh The Biomes You'll Go (by AOCAWOL)
Cultural Delights (by NCP_Bails)

### Loader

Forge

### Loader Version

Forge 42.2.14

### API Version

?

### Mod Version

polymorph-forge-0.46.4+1.19.2.jar

**Comment by TheIllusiveC4** [comment]
Have you tried in the vanilla crafting table? Which recipe conflict did you try specifically? Does it work if you downgrade to polymorph-forge-0.46.1+1.19.2?

**Comment by MrTangoPIG** [comment]
Nvm, im dumb, it is working. Wasn't finding recipes with multiple outputs.
