### ISSUE TITLE
[Bug]: Minecraft crashes when rendering screen with Polymorph mod

### ISSUE THREAD

**Issue by YumatanGames** [TheIllusiveC4/Polymorph#228]
### Minecraft Version

1.20.1

### What happened?

Hi there,

I've been experiencing some crashes while playing Minecraft with the Polymorph mod installed. The crash seems to be occurring when the game is rendering the screen.

Here are the important details from the crash report:

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1735.method_7681()" because "containerScreen.field_2787" is null
    at net.minecraft.class_332.handler$hjc000$equipmentcompare$renderTooltip(class_332.java:6342)
    at net.minecraft.class_332.method_51446(class_332.java)
    at com.illusivesoulworks.polymorph.api.client.widget.SelectionWidget.renderTooltip(SelectionWidget.java:119)
    
This error seems to be occurring when Polymorph is trying to render a tooltip, but containerScreen.field_2787 is returning null.

Just for the record, I previously suspected that the Almost Unified mod could be causing conflicts with Polymorph, leading to this crash. However, in this recent crash, Almost Unified was not active, so it seems to suggest that the issue lies either with Polymorph or its interaction with another mod or game element.

Any help on this would be greatly appreciated!

Thanks,

### How do you trigger this bug?

On my modpack, just take an item with multiple recipes (like copper ingot, for instance) and when clicking on the polymorph icon, the game crashes to desktop.

The modpack can be found here:
https://modrinth.com/modpack/reimagined-vanilla

### Loader

Quilt

### Loader Version

Quilt Loader 0.19.2

### API Version

Quilted Fabric 7.0.5+0.84.0-1.20.1

### Mod Version

0.49.0+1.20.1

### Relevant Log Outputs

[crash-2023-07-13_08.19.09-client.txt](https://github.com/illusivesoulworks/polymorph/files/12040598/crash-2023-07-13_08.19.09-client.txt)
[crash-2023-07-13_08.37.36-client.txt](https://github.com/illusivesoulworks/polymorph/files/12040599/crash-2023-07-13_08.37.36-client.txt)
[crash-2023-07-13_08.41.19-client.txt](https://github.com/illusivesoulworks/polymorph/files/12040602/crash-2023-07-13_08.41.19-client.txt)

**Comment by erazare** [comment]
concur having same exact issue same version 👍 
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.inventory.Slot.m_6657_()" because "containerScreen.f_97734_" is null

**Comment by erazare** [comment]
it is not polymorph.. i systematically hunted this one down, it is explicitly the equiptment compare mod and it doesnt only do it with polymorph it will also crash anytime you make a trade of any kind
