### ISSUE TITLE
[Bug]: Incompatibility with charm

### ISSUE THREAD

**Issue by mattcloud4** [TheIllusiveC4/Polymorph#230]
### Minecraft Version

1.19.2

### What happened?

Charm's sort inventory feature seem to conflict with polymorph. The polymorph button doesn't appear when charm is enabled.

### How do you trigger this bug?

1. Using charm with polymorph

### Loader

Fabric

### Loader Version

0.14.19

### API Version

0.76.0

### Mod Version

1.16.1 + 1.19.2

**Comment by TheIllusiveC4** [comment]
I am unable to reproduce this, as installing Charm and Polymorph together and no other mods the button still appears for me when recipe conflicts occur. Did you make sure to test this with a known recipe conflict? It's also possible that this has somehow been resolved on Charm's end in the interim.
