### ISSUE TITLE
[Bug]: Recipe not switching

### ISSUE THREAD

**Issue by Parabellum996** [TheIllusiveC4/Polymorph#233]
### Minecraft Version

1.18.2

### What happened?

Dynamic Trees has a bug with Polymorph. It will not change the recipe for the trees. It also disables the use of tools on the dynamic trees as well.

Dynamic Trees is on version 1.0.4. 

### How do you trigger this bug?

1.
2.
3.
...

### Loader

Forge

### Loader Version

40.2.10

### API Version

N/A

### Mod Version

1.18.2-0.49

**Comment by LiAuTraver** [comment]
Same question for me too. 1.20.1

**Comment by TheIllusiveC4** [comment]
I'm not sure I understand correctly, can you provide a more detailed explanation and outline the steps to reproduce this? I've tested this on my end and there doesn't seem to be any noticeable recipe conflicts from Dynamic Trees, all the seeds have different ingredients, and a Diamond Axe works as expected on a grown tree.

**Comment by LiAuTraver** [comment]
Sorry for my late response. As for me, the problem disappeared after I removed fast bench series. 
Thank you and sorry for the inconvenience I caused. ❤️

**Comment by TheIllusiveC4** [comment]
If it's the Fast mods giving you issues, then make sure you've updated Polymorph to the latest version as that issue has been fixed already.
