### ISSUE TITLE
[Feature]: Halt until recipe is chosen

### ISSUE THREAD

**Issue by littlewing1977** [TheIllusiveC4/Polymorph#236]
### What is the new feature or improvement?

I have some mods installed that allow the possibility of smelting or crafting very fast.  So several items are created before I can switch the recipe.  It would be great if you could add a setting that would allow you to halt the smelting/crafting until a recipe is chosen. (If that's possible.)

**Comment by TheIllusiveC4** [comment]
While it would be a nice QoL feature, it would be very tricky to implement and I'm not sure it's even feasible. It would involve some pretty invasive hooks into furnaces/crafters and would probably hurt more often than help, all things considered.
