### ISSUE TITLE
[Bug]: Game crashed during setup

### ISSUE THREAD

**Issue by Rimuchii** [TheIllusiveC4/Polymorph#238]
### Minecraft Version

1.20.1

### What happened?

Crash while booting up the game with `java.lang.NoClassDefFoundError` error, appeared to be the case with every mods related to spectrelib :(

### How do you trigger this bug?

1.enable any of the mods containing spectrelib
2.launch the game
3.crash even before the game open

### Loader

Fabric

### Loader Version

Fabric - 0.14.23

### API Version

Fabric 0.89.3

### Mod Version

0.49.0+1.20.1

### Relevant Log Outputs

https://paste.gg/p/anonymous/0faa53b096424fea8f30f64c0f61f471

**Comment by Abalieno** [comment]
Happens in 1.19.2 after updating to fabric loader 0.14.23

**Comment by Poopooracoocoo** [comment]
As a workaround, you can downgrade Fabric Loader to 0.14.22.

Also see https://github.com/illusivesoulworks/spectrelib/issues/3
