### ISSUE TITLE
[Bug]: Polymorph Button not showing up (?) 1.19.2

### ISSUE THREAD

**Issue by clovcr** [TheIllusiveC4/Polymorph#239]
### Minecraft Version

1.19.2

### What happened?

Hi! 

The polymorph button to switch to a different recipe isn't showing up? 

I found it wasn't appearing when I was using a lot of mods, so I tested it with just one mod (woodworks) which has always worked with it before but had the same issue.
I don't know if this is a bug or not as I could be doing something wrong on my end.

If anything else is needed, please let me know! (I don't really know what I'm doing :I)

Thanks! :D

### How do you trigger this bug?

1. Load minecraft
2. Go to craft, e.g. Chest 
3. Try to craft vanilla chest, put in spruce planks result is spruce chest from woodworks 
4. Cant switch due to no button :<
![Test Without multiple mods (only woodworks)](https://github.com/illusivesoulworks/polymorph/assets/116544957/253bd41d-3665-4cfe-86e7-2d3250298d92)

### Loader

Forge

### Loader Version

Forge - 43.3.0

### API Version

N/A

### Mod Version

Polymorph 0.46.4

### Relevant Log Outputs

[latest.log](https://github.com/illusivesoulworks/polymorph/files/12840395/latest.log)

**Comment by hallool** [comment]
same here

**Comment by hallool** [comment]
just re installed it now it works

**Comment by clovcr** [comment]
imma close it cus it works now for me too lol, thanks for your time tho!
