### ISSUE TITLE
[Feature]: compatiblity 1.19.2

### ISSUE THREAD

**Issue by hi4444** [TheIllusiveC4/Polymorph#243]
### What is the new feature or improvement?

can you make it work with the crafting station mod by tfarecnim

**Comment by SGZ-Creations** [comment]
I second this one
https://www.curseforge.com/minecraft/mc-mods/crafting-station

**Comment by TheIllusiveC4** [comment]
Duplicate of https://github.com/illusivesoulworks/polymorph/issues/197
