### ISSUE TITLE
[Bug]: Two Shulker Box recipes, one deletes all items

### ISSUE THREAD

**Issue by Zunwolf1896** [TheIllusiveC4/Polymorph#245]
### Minecraft Version

1.20.1

### What happened?

A player put a Shulker box and dye into inventory to change the colour. They clicked on the Shulker to grab it once it was recoloured and all items had been deleted. 

We realized there are two recipes for Shulker box showing up, the default one deleted any items inside, if you choose polymorph to change the box, it keeps all items. 

### How do you trigger this bug?

1. Place Shulker box, with items inside, into a craft grid along side a dye colour of choice. 
2. Click on the Shulker box in the completed crafting box, do not change it using the Ploymorph button.
3. See your items have been dispensed into the void.
...

### Loader

Fabric

### Loader Version

Fabric - 0.14.23

### API Version

Fabric-api-0.90.7+ 1.20.1

### Mod Version

polymorph-fabric-0.49.0+ 1.20.1

### Relevant Log Outputs

There are no logs, nothing shows in the console when the person chooses the box, I have a couple images of it, though. 

<img width="1440" alt="Screenshot_2023-11-16_at_19 32 49" src="https://github.com/illusivesoulworks/polymorph/assets/88537204/097cc468-2e18-4799-8d70-4503fde0457e">
<img width="1440" alt="Screenshot_2023-11-16_at_19 32 47" src="https://github.com/illusivesoulworks/polymorph/assets/88537204/322226b3-7b14-4a29-b15c-ad8a3020ba16">

**Comment by TheIllusiveC4** [comment]
I cannot reproduce this, as trying this out with just Polymorph doesn't yield anything except the single Shulker Box result that doesn't delete any items. The most likely possibility is that this is a mod conflict, likely tied to whatever is granting these additional Shulker Box results, and a side effect of having Polymorph installed is that some of these "incorrect" results are being shown when usually they'd be hidden. I recommend trying this with just Polymorph installed to verify it's a mod conflict and then trying to figure out which mod is causing this.
