### ISSUE TITLE
[Bug]:  Polymorph Button not showing

### ISSUE THREAD

**Issue by xd4rkzghost01** [TheIllusiveC4/Polymorph#254]
### Minecraft Version

1.20.1

### What happened?

Hi ! Just encounter this issue. As the title say, the button is not showing when trying different recipe. The sad part is, it is a modpack that a build for fun... so i don't know wich mod can cause the issue.
![2024-02-29_04 00 45](https://github.com/illusivesoulworks/polymorph/assets/63568312/f7650d95-c212-4928-b01d-24847afe0e9a) In the screenshot, i got the Smoked Rotten Flesh (from Born in Chaos), but can't get the button to switch for Leather (from JRFTL)

### How do you trigger this bug?

1.  Can't find a way to "reproduce" the bug.
2. Might think you can help me find what is doing this, because in 1.19.2 i have almost the same mods install and din't have this issue and since i can find a "similar" issue, i'm making this one.
3. There the modlist
[Modlist.txt](https://github.com/illusivesoulworks/polymorph/files/14445786/Modlist.txt)

### Loader

Forge

### Loader Version

Forge 47.2.18

### Mod Version

Polymorph 0.49.2 + 1.20.1

### Relevant Log Outputs

This is the latest log (in a new world)
[latest.log](https://github.com/illusivesoulworks/polymorph/files/14445723/latest.log)

Edit: Here another log with only Optifine, Born in Chaos and JRFTL. As in BiC, we can smoke rotten flesh to get smoke meat, i want to have the option to get the leather from JRFTL, but the button don't appear there too.
[Isolated Log](https://github.com/illusivesoulworks/polymorph/files/14453081/latest.log)

**Comment by Gortius** [comment]
Try removing mods related to inventory UI or management, in my case "Stack to Nearby Chests" mod was the problem for me, i removed it and the mod worked perfectly after that

**Comment by xd4rkzghost01** [comment]
I've try 1 by 1 aaaaaall the mod i had in my modpack.... to finally found the only 1 that cause the issue : Optifine
[Without Optifine](https://github.com/illusivesoulworks/polymorph/files/14545081/latest.log)

[With Optifine](https://github.com/illusivesoulworks/polymorph/files/14545096/latest.log)

I know Optifine is a close source and i dunno why it causing this but it delete the Polymorph button on this version.

**Comment by TheIllusiveC4** [comment]
Unfortunately if the issue is due to Optifine then there's not much I can do on my end.
