### ISSUE TITLE
[Bug]: Polymorph not showing  up.  

### ISSUE THREAD

**Issue by RaeShePlays** [TheIllusiveC4/Polymorph#258]
### Minecraft Version

1.19.2

### What happened?

Randomly today polymorph stopped  working.  In the pack I  was on I had over 300 mods so I  started a new  modpack with  just   polymorph and  quark.  Mod did not show and the  chest would only  show as the  quark   type.  so  Oak or  birch chest, not  basic chests.   I removed quark and added that I like wood and comforts.  I looked for  conflicts. there were none. No icon on the  workbench.  I  then loaded a third modpack  1.20.1  version and it did not  show there either.  I tried  another modpack 1.19.2 and Polymorph did show  up. I know in the last 12-24 hours polymorph was working.  I was adding  and removing mods on the first one  because I was dealing with conflicts with other mods. I think it was working after I  got all the mods sorted out, but cannot be 100% on that.  Thus me trying it on a blank slate with no prevail.  I am most confused as to why it's not working when I only  had  4 mods installed.   I am now going to look over the two mods  by the same person to see if I can  find a conflict. 

**Edit;**  In a  final  attempt to figure this out I  deleted the  original modpack  Cottage Witch, and  downloaded it again fresh.  Polymorph showed up.  Despite it not showing up on the original  version I already had....  I  got  nothing here. 

**Second Edit** After getting polymorph to show I  created a copy to start removing mods I didn't want from the org modpack. Nothing that I could see as  major has been removed, I've  been constantly testing new worlds out   between editing the modpack.  It currently has a mod that  keeps the  items  and  shows a 3D  version of what you are crafting.  I closed the crafting bench accidently  after seeing Polymorph working.  I opened the  crafting bench and Polymorph was not showing. I   crafted the quark  chest and Polymorph showed  back  up.  I repeated the closing  and  reopening of the crafting bench and  it showed  up  again. I did this  trial a second time.  This time manually taking the  items out of the crafting bench and putting them  back  in and they  showed  up.  I am  about to  try my original  modpack  to see if this  fixes it. s. I will keep  trying to find  what triggers this issue. 

Modpacks I  tried it with
Cottage witch  by HeyKatu  Failed to show  up including removing  almost all mods
Better MC  by  SHXRKIE Failed  to show  up
Cottage Witch  Recast by HeyKatu  Showed  up. 

### How do you trigger this bug?

1.Lots
2. See  above
3.
...

### Loader

Fabric

### Loader Version

43.3.5

### Mod Version

0.046.5+1.19.2

**Comment by RaeShePlays** [comment]
Update;  after a few days of  fixing my modpack I found at least one of the culprits is "Silent  Gear"  It's the only mod I added this afternoon and Polymorph stopped working.  The second I removed it  Polymoprh worked again.   I repeated  adding and deleting said mod to a few saves with the same outcome.

**Comment by RaeShePlays** [comment]
I never  found a true solution to my  issue, but I've moved on to a new modpack and it's mostly working so I am closing this ticket.

**Comment by TheIllusiveC4** [comment]
> I never found a true solution to my issue

Was the problem not "Silent Gear" as you noted in your previous comment, or did the issue appear again in another capacity beyond that?
