### ISSUE TITLE
Oh, How the Crafting Has Tabled! Mod support

### ISSUE THREAD

**Issue by nokteholda** [TheIllusiveC4/Polymorph#26]
**Please describe the new feature or change.**
Mod support to "Oh, How the Crafting Has Tabled!" for fabric
**Please describe why you want this feature.**
Because this mod have crafting table from all planks (ex. Crimson Crafting Table, etc.)

**Comment by TheIllusiveC4** [comment]
Implemented in the 0.0.6 release.
