### ISSUE TITLE
[Bug]: Not changing the output regardless of what recipes I select in blast furnace

### ISSUE THREAD

**Issue by ionutsoran** [TheIllusiveC4/Polymorph#261]
### Minecraft Version

1.20.1

### What happened?

I Have 4 conflicting recipes for the blast furnace when creating steel and pig iron they both use iron as base in the blast furnace but when I try to select the second option from polymorph it doesn't do anything and it reverts to the first recipe it finds!
Input
![image](https://github.com/illusivesoulworks/polymorph/assets/19574829/3fc1fc14-fa9c-4a0e-91f1-9cdf09adc731)
Output
![image](https://github.com/illusivesoulworks/polymorph/assets/19574829/fd021f4f-9200-452e-a9b4-c9e01274a843)

### How do you trigger this bug?

1. I put iron in the blast furnace
2. I select the recipe from the list in polymorph (sometimes it only shows after starting the smelting process)
3. And I always get the first recipe from the list regardless of what I select in polymorph interface

### Loader

Forge

### Loader Version

Forge-47.2.0

### API Version

N/A

### Mod Version

polymorph-forge-0.49.3+1.20.1

**Comment by ionutsoran** [comment]
I'm also using crafttweaker, I'm not sure if its relevant. I don't modify anything except for the bread recipe

**Comment by TheIllusiveC4** [comment]
Can you try testing this with _only_ Polymorph and the mods that use the ingots involved? This is to see if it's potentially a mod conflict with something else in your environment.

**Comment by ionutsoran** [comment]
Hello there! I seems that when I only use the mods and the ingots involved now the polymorph symbol doesn't even show up anymore on single player
![image](https://github.com/illusivesoulworks/polymorph/assets/19574829/0023d035-cb0b-4c21-b9b4-5ad0e6024eec)
As you can see I have more than one recipes for steel
![image](https://github.com/illusivesoulworks/polymorph/assets/19574829/b7cbe3fa-74fe-4dec-b257-a270c548cab9)
These are the only mods I use
![image](https://github.com/illusivesoulworks/polymorph/assets/19574829/ef972e9b-2b8a-4a52-a8bc-239e5619193d)

**Comment by ionutsoran** [comment]
I ran the mods separately and they work. I found the culprit. And managed to fix it. The bug comes from recipe-essential mod. However I used the fabric version with the forgified-api and it messes up big time. So i downloaded the forge version for it and they work perfectly together. 
Bottom line is that you can close this issue!
