### ISSUE TITLE
[Bug]: Polymorph seemingly causing Spectrum features to break

### ISSUE THREAD

**Issue by Kekulism** [TheIllusiveC4/Polymorph#262]
### Minecraft Version

1.20.1

### What happened?

On my modified version of the BigChadGuys Plus modpack, i've found that multiple aspects of the Spectrum mod just do not function, whether on my server or a singleplayer world. I've found that the console on my server outputs an error when trying to use Spectrum Mod's Potion Workshop block. That error can be read in the pastebin link. My limited experience with identifying problems in modpacks leads me to notice that three mods are mentioned in the error-- Spectrum, Recipe Essentials, and Polymorph. I removed Recipe Essentials since it could function server-side or client side but the issue still persisted, though this time without Recipe Essentials in the error. I dont know how to fix this myself and I would rather not remove PolyMorph or Spectrum from the modpack. Any help with this would be greatly appreciated

### How do you trigger this bug?

1. Use Spectrum and Polymorph
2. Try to use the Potion Workshop to craft something

### Loader

Fabric

### Loader Version

Fabric 0.15.11

### API Version

Fabric API 0.92.1

### Mod Version

0.49.3

### Relevant Log Outputs

https://pastebin.com/mdHXXRMe

**Comment by Kekulism** [comment]
Quick Revision: I noticed that in the pastebin error I included it doesnt mention Polymorph. That error was from having all 3 of the mods installed, and it was only when I disabled RecipeEssentials that PolyMorph showed up in the error. I realize now that this may be an issue with Spectrum rather than PolyMorph so I apologize if I'm wasting your time with this.

**Comment by TheIllusiveC4** [comment]
Can you provide the log that shows Polymorph's error?

**Comment by Kekulism** [comment]
Sure. I logged into my singleplayer world and tried to make Water with Spectrum's Potion Workshop and then closed the game. Here's the latest.log 
[latest.log](https://github.com/illusivesoulworks/polymorph/files/15378578/latest.log)

**Comment by Kekulism** [comment]
Oh by the way, I've since tried to see what would happen if I remove PolyMorph from my server's mods, and after doing that the Spectrum features worked. I was able to use the Potion Workshop with no issues. Same for crafting enchantments at the enchanter, though as far as I could tell the console never sent an error regarding the Enchanter, only the Potion Workshop.

**Comment by TheIllusiveC4** [comment]
I believe that error is coming from Item Obliterator. Can you try removing that mod and see if the error still occurs?

**Comment by Kekulism** [comment]
Nope, error still persists with Item Obliterator turned off. The Potion Workshop still does not function, though despite this the error that was printed in the log is gone, so I suppose that error was actually unrelated to the real issue.

**Comment by TheIllusiveC4** [comment]
I've tested this on my end with just Spectrum and Polymorph and unfortunately I cannot reproduce this. I've tried both brewing and crafting in the Potion Workshop and they both work as expected.

1. Which recipes did you try when you tested this?
2. Can you test with _only_ Spectrum (and its dependencies) and Polymorph and see if the issue persists? If not, this may be the result of an unidentified conflict with another mod in your pack.
