### ISSUE TITLE
[Feature]: compatibility with mods that add elytra trim textures

### ISSUE THREAD

**Issue by 6xolotl** [TheIllusiveC4/Polymorph#269]
### What is the new feature or improvement?

in particular im talking about Elytra Trims and Armor Restitched, which both add their own unique trim patterns for elytra.

from what ive heard, polymorph is meant to show a button in the smithing table too. but when i tried to apply a trim to my elytra with both ET and AR installed, it just layered the trim textures on top of each other, with no polymorph button to be found. im assuming this isnt a bug, just a feature that isnt currently in the mod, hence the enhancement tag.

the ability to cycle between different mods's trim textures on the elytra would be wonderful. the customizability would be endless!

i completely understand if this would be too time consuming to implement, but i thought it was worth a shot to suggest it. have a lovely day!!

**Comment by TheIllusiveC4** [comment]
I looked into this, and I think the main issue is that Elytra Trim does not synchronize its recipe with the client. This causes Polymorph to fail to find the recipe when it shows you your available choices. Normally, I'd try to figure something out that would fix this, however the more important thing I wanted to note is that addressing this actually wouldn't change anything. No matter which recipe you choose, having both mods installed will cause the final result to overlay their respective textures. For that reason, there would be no purpose is addressing this.
