### ISSUE TITLE
[Crash]: It Crashma Game 1.21 | | Tough As Nails and Polymorph Conflicted.

### ISSUE THREAD

**Issue by makumaku1974** [TheIllusiveC4/Polymorph#272]
### Minecraft Version

1.21.0

### What happened?

Water Purifier caused a ticking entity that crashma game.

### How do you trigger this bug?

1. You must have Tough As Nails along with its dependencies
2. Then Polymorph
3. Find Water Purifier [Can be found in the Creative Tab]
4. Dispense water to any canister and head for the water purifier
5. Gather some charcoal (Coal is nono)
6. Like you would smelt in furnace the charcoal is place below the water canister and boom. Crashma Game.

### Loader

Fabric

### Loader Version

0.15.11

### API Version

0.100.3

### Mod Version

1.0.0 - 1.21

### Relevant Log Outputs

[crash-2024-06-26_20.42.54-server.txt](https://github.com/user-attachments/files/16008169/crash-2024-06-26_20.42.54-server.txt)

**Comment by TheIllusiveC4** [comment]
This bug is already fixed as of version 1.0.1+1.21.
