### ISSUE TITLE
[Bug]: Doesn't work on 1.20.1 at all.

### ISSUE THREAD

**Issue by KhaozEatR** [TheIllusiveC4/Polymorph#280]
### Minecraft Version

1.20.1

### What happened?

The button doesn't show up in the crafting table even when I have no other mods installed. Does the button show up even when you have nothing else installed? If you need to have something installed for the button to show up, then I will need to do some more troubleshooting to narrow down conflicts. 

### How do you trigger this bug?

1. Spawned into a new world
2.Made a crafting table
3. Opened up the crafting table interface.

### Loader

Forge

### Loader Version

Forge- 47.3.0

### API Version

N/A

### Mod Version

Polymorph 0.49.5

**Comment by Fischake** [comment]
Bump for fabric 1.20.1 as well. Even tested on a new instance through prism with nothing but Polymorph and Multitools and still no luck,

**Comment by dragonmaus** [comment]
Also here:
Minecraft 1.20.1
Fabric 0.16.0
Polymorph 0.49.5

**Comment by uczpre** [comment]
The button is suppose to only show up when there IS a recipe conflict , ofc it doesnt show up when the only mod installed is polymorph lol , read the modrinth page.
https://modrinth.com/mod/polymorph

close the issue @KhaozEatR

**Comment by dragonmaus** [comment]
I can't speak to the "no other mods installed" thing, but it is absolutely not showing up in Fabric on 1.20.1, despite there most definitely being conflicts.

**Comment by KhaozEatR** [comment]
Hm...in that case then it's definitely having a problem with the Supplementaries Mod. After some more troubleshooting. The alternative recipes for my other mods show up except for the chest recipes in Supplementaries. Luckily I can craft a hopper with an oak chest just as much as I can with a vanilla chest. Just the only way to get a vanilla chest is to find one in the wild somehow. Supplementaries replaces vanilla chests in structures as well.

**Comment by KhaozEatR** [comment]
I'll continue to do more troubleshooting, but for now I think I'll close this subject.
