### ISSUE TITLE
[Bug]: Many errors in the server log

### ISSUE THREAD

**Issue by YOUNIN15** [TheIllusiveC4/Polymorph#281]
### Minecraft Version

1.20.1

### What happened?

When I have Polymorph when I start the server I get a lot of errors in the registry. It should be noted that the mod is working (for the moment) but in the registry appear many errors

### How do you trigger this bug?

1. Install Polymorph
2. Start the server
3. Many errors in the registration

### Loader

Fabric

### Loader Version

Fabric 0.16.0

### Mod Version

polymorph-fabric-0.49.5+1.20.1

### Relevant Log Outputs

https://mclo.gs/TDQGqMa

https://paste.gg/p/anonymous/e313fb5ee1724122969d84f210a2b8a2

![image](https://github.com/user-attachments/assets/a309f78c-aa30-4626-af4f-a18a26a4b49e)

**Comment by YOUNIN15** [comment]
I made a mistake when I put the version of minecraf, it is 1.20.1 in which these errors appear, I edited it and put the correct version.

**Comment by TheIllusiveC4** [comment]
It's alright, I recognized the mod version as being 1.20.1. The new update that fixed it is also only for 1.20.1.
