### ISSUE TITLE
[Feature]: 1.20.1 support

### ISSUE THREAD

**Issue by uczpre** [TheIllusiveC4/Polymorph#282]
### What is the new feature or improvement?

Most mods , especially the big ones that add a bunch of recipes , still only support 1.20.1 and will only support 1.20.1 for the time being. Its weird that this mod doesnt have constant support for this version.......

**Comment by TheIllusiveC4** [comment]
I'm not sure what you mean, this mod currently supports 1.20.1 and this version still receives bug fixes as needed.
