### ISSUE TITLE
[Bug]: Game crashes when using the fill recipe short cut

### ISSUE THREAD

**Issue by ffuentesm** [TheIllusiveC4/Polymorph#286]
### Minecraft Version

1.21.1

### What happened?

The game crashes when I try to shift-click a recipe into the crafting table. 

Not sure if is a JEI or a Polymorph error. On the log, it shoes the Polymorph API on the code trace. 

### How do you trigger this bug?

Shick Click on a recipe when crafting

### Loader

NeoForge

### Loader Version

21.1.65

### Mod Version

polymorph-neoforge-1.0.6+1.21.1

### Relevant Log Outputs

https://pastebin.com/U3qrLkvz

**Comment by TheIllusiveC4** [comment]
I'm unable to reproduce this, using Polymorph, JEI, and EMI I am able to fill the recipe as expected. I also cannot see the line that you're referring to in the logs from the Polymorph API, I just see EMI and JEI. Have you tested with _just_ those three mods installed? Does the error still occur if you remove Polymorph?

**Comment by ffuentesm** [comment]
Seems the problem was on the JEI end. They been making some API changes and that was affecting EMI.
