### ISSUE TITLE
[1.16.3] Crash with BYG update.

### ISSUE THREAD

**Issue by ProsperCraft** [TheIllusiveC4/Polymorph#32]
#### Versions (Be specific, do not write "latest"):
* Polymorph: polymorph-forge-1.16.3-0.15
* Forge/Fabric: byg-1.1.0-ALPHA-v3

https://gist.github.com/ProsperCraft/30974b6aa59042bc0808811095e444f1

**Comment by BedrockLegends** [comment]
Ran into this same issue as well

**Comment by CorgiTaco** [comment]
Considering BYG's latest file is Alpha, it's debatable whether or not to change the file path to the alpha's.

**Comment by BedrockLegends** [comment]
There should be some kinda of release this weekend to fix this

**Comment by CorgiTaco** [comment]
@BedrockLegends Dont rush them please.

**Comment by TheIllusiveC4** [comment]
For context @BedrockLegends was probably referring to a comment I made on Discord. I do plan on making an update this weekend to address this issue.
