### ISSUE TITLE
1.15.2 version requires 1.16 forge version

### ISSUE THREAD

**Issue by autumnhour** [TheIllusiveC4/Polymorph#34]
Polymorph for 1.15.2 requires Forge 31.2.5 which is for MC 1.16

**Comment by TheIllusiveC4** [comment]
This is incorrect, it is a 1.15.2 version.

https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.15.2.html

**Comment by autumnhour** [comment]
Is this a joke, you sent a link which states forge for 1.15.2 latest version is 31.2.45. The mod requires 31.2.5???

**Comment by TheIllusiveC4** [comment]
Yes, those are both correct. 31.2.5 came before 31.2.45 since 5 is less than 45. I'm sorry if that comes off as condescending, I'm just not sure how else to put it. The 31.2.5 version is on that same page that I linked you for 1.15.2, you can check it yourself.
