### ISSUE TITLE
Server crashes with 0.17

### ISSUE THREAD

**Issue by zwibblTV** [TheIllusiveC4/Polymorph#38]
Versions:
* Polymorph: polymorph-forge-1.16.4-0.17.jar
* Forge: forge-1.16.4-35.1.0.jar

Observed Behavior: Server crashes on start

Crash Log: https://hasteb.in/mecowaju.rb

**Comment by NomSTee** [comment]
I believe im having the same issue, 
https://hasteb.in/bufexeyu.rb

**Comment by TwilightPSN** [comment]
same issue here

https://gist.github.com/TwilightPSN/123d4788ce27e5fb4bf9a8ffd639c874

**Comment by TheIllusiveC4** [comment]
Whoops, sorry about that. I'll have an update out momentarily.
