### ISSUE TITLE
Polymorph not able to detect conflict

### ISSUE THREAD

**Issue by D-Bigboy-302** [TheIllusiveC4/Polymorph#4]
Game Version: 1.15.2
Forge Version: 31.2.20

I have a recipe conflict from Quark and Doggytalents. The rope from Quark and the wool dog collar from Doggytalents. It doesn't appear in the conflict logs as well.

While I'm posting this, I'd also like to request compatibility for Vanilla Tweaks crafting Pad.

I needed a mod like this for AGES! Thank you for making it!

**Comment by TheIllusiveC4** [comment]
Are you sure there's supposed to be a conflict? The default recipes for the Quark Rope and the Doggy Talents Wool Dog Collar are 6 strings and 8 strings respectively and do not conflict.

I'll look into the Vanilla Tweaks Crafting Pad compatibility.

**Comment by D-Bigboy-302** [comment]
Oh! My mistake! Seems that they changed the recipe in one of the updates! I had memorized the old recipe. Or at least I thought lol Apologies.

Either way, thank you for your time!
