### ISSUE TITLE
Shuffle button not showing anywhere

### ISSUE THREAD

**Issue by AdnanuReeves** [TheIllusiveC4/Polymorph#41]
#### Versions (Be specific, do not write "latest"):
* Polymorph: polymorph-forge-1.16.4-0.18.jar 
* Forge/Fabric: Forge 35.1.7
#### Steps to Reproduce: I dont know

Crash Log: Too big for paste sites :(
[latest.log](https://github.com/TheIllusiveC4/Polymorph/files/5613157/latest.log)

**Comment by TheIllusiveC4** [comment]
Please try and reproduce this issue without any other mods first. If it's a mod incompatibility, please reduce the number of mods to the amount minimal necessary to reproduce the issue.

**Comment by 53901** [comment]
AdnanuReeves
may i ask if the issue was solved. and if it was a mod conflict. 
i would appreciate ur response, for i am experiencing the same issue.
