### ISSUE TITLE
Polymorph button issues in specific crafting situations

### ISSUE THREAD

**Issue by sunnyughs** [TheIllusiveC4/Polymorph#43]
Versions:
* Polymorph: [1.16.3-0.16](https://www.curseforge.com/minecraft/mc-mods/polymorph/files/3093134)
* Forge/Fabric: 1.16.3 - 34.1.42

Refined Storage - [v 1.9.9](https://www.curseforge.com/minecraft/mc-mods/refined-storage/files/3111240)
![image](https://user-images.githubusercontent.com/26176279/101780914-2a71c700-3ac5-11eb-9a69-07e62e83a94a.png)

Crafting Station - [v 4.1.1](https://www.curseforge.com/minecraft/mc-mods/crafting-station/files/3084325)
![image](https://user-images.githubusercontent.com/26176279/101780696-d5ce4c00-3ac4-11eb-9c53-fe0d7f667a89.png)

**Comment by TheIllusiveC4** [comment]
I believe these are fixed in more updated Polymorph versions. I see that you're on 1.16.3, but I believe Polymorph 0.18 should still work on that version. Could you try that and verify for me?

**Comment by sunnyughs** [comment]
It is indeed fixed on Polymorph 0.18 on 1.16.3. 

Thanks!
