### ISSUE TITLE
Feature Request: Add Support for two Mods.

### ISSUE THREAD

**Issue by smallerYeet** [TheIllusiveC4/Polymorph#44]
**Please describe the new feature or change.**
There are two mods that you should add your Support to!
First is [Crafting station](https://www.curseforge.com/minecraft/mc-mods/crafting-station).
Second is [Simple Storage Network](https://www.curseforge.com/minecraft/mc-mods/simple-storage-network/).

This would be very nice. I run a Mod pack that focuses around more Vanilla style and thus those mods are in. I always have to keep a Vanilla Crafting Table since it's only possible to craft my stuff there and not in my storage system (or in early game at the bench)

**Comment by TheIllusiveC4** [comment]
What version of Polymorph are you using? They should already be compatible.

**Comment by smallerYeet** [comment]
I use an Old version and just upgraded. So I wasn't able to try out if it works, sorry then!

**Comment by TheIllusiveC4** [comment]
Okay then. If they still don't work in the newest version, then submit a bug report and I'll check it out.
