### ISSUE TITLE
Crash when Smelting with [Create] GUI-less furnace alternative

### ISSUE THREAD

**Issue by Djgione** [TheIllusiveC4/Polymorph#45]
#### Versions:
* Polymorph: 1.16.4-0.19
* Forge: 1.16.4-35.1.13
#### Observed Behavior:
Attempting to use an encased fan from Create Mod [1.16.3v-0.3] 
Used with lava in order to smelt iron ore into iron ingots.
Crashed before the ore turned to ingots. Server kicks all players.
#### Expected Behavior:
Iron Ore should have smelted into iron ingots.
Smelting occurs by dropping on floor in front of an encased fan pushing air through lava.
#### Steps to Reproduce:
1. Create and power encased fan.
2. Have encased fan push air towards lava.
3. Drop a smeltable item into the particles flowing from lava.
4. Crash when server attempts to smelt.

Crash Log: https://pastebin.com/M4Sv6rx1

**Comment by TheIllusiveC4** [comment]
Unfortunately, I cannot reproduce your issue. Following your steps, I can successfully smelt my item. However, the cause of your issue is plain to me so regardless I've attempted a fix with Polymorph 0.20. Please give the new version a shot and see if the issue still persists, then let me know the results.

**Comment by Djgione** [comment]
Great job, patch works great and the crash has been stopped. Appreciate the quick response.

**Comment by Vaelzan** [comment]
To add a little context for why it couldn't be reproduced, the crash only occurs when FastFurnace is also present, so just Polymorph and Create alone wouldn't trigger it.

Thanks for the quick fix, C4!
