### ISSUE TITLE
[1.16.4] Polymorph button shows up top left in Creative Inventory (and button is always shown in normal inventory.)

### ISSUE THREAD

**Issue by Gbergz** [TheIllusiveC4/Polymorph#49]
#### Versions
* Polymorph: 1.16.4-0.20
* Forge/Fabric: **Forge**
#### Observed Behavior: 

Button is being being shown in the creative inventory despite no crafting window is shown.

#### Expected Behavior: 
No Polymorph button in Creative Inventory.
#### Steps to Reproduce: 
1. Go into Creative
2. Look top left
3. There it is.
...

Screenshot:
![image](https://user-images.githubusercontent.com/26634554/102907091-d3310680-4475-11eb-9b7f-df35acb90d27.png)

**Additional information:**
The button is also always shown when theres no recipe to be output **gif example**: (this might be tied to the first issue)
https://gyazo.com/911952541bf1f60e332ff88eee4b7a3b

**Comment by TheIllusiveC4** [comment]
It sounds like some mod(s) are adding empty recipes. Can you reproduce this with only Polymorph installed?

**Comment by Gbergz** [comment]
Appears its not an issue when the mod is on an empty instance. Though this started happening with one of the recent updates to Polymorph. ``polymorph-forge-1.16.4-0.16.jar`` which is no longer available did work. No random button anymore.

Was going to revert to that but since it's no longer available I tried 0.15, but that didn't even let me boot my game.
