### ISSUE TITLE
Polymorph button not appearing for crafting table (1.16.4)

### ISSUE THREAD

**Issue by onemorelevel0** [TheIllusiveC4/Polymorph#50]
#### Versions (Be specific, do not write "latest"):
* Polymorph: 1.16.4, most recent update (worked fine before furnace update)
* Forge/Fabric: forge
#### Steps to Reproduce:
1. no button to switch between recipes in crafting table, but it works for furnace
2. button to switch between recipes in shapeless crafting & crafting table
3. have mod on and try to use a recipe with multiple recipes in shapeless crafting or crafting table
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by TheIllusiveC4** [comment]
Can you reproduce this with only Polymorph installed? If not, you'll need to isolate the minimum number of mods needed to reproduce this issue.

Also, I'll need to know which conflicting recipes you tried.

**Comment by SaytoROG** [comment]
I have the Same Problem
Polymorph: 1.16.4
Forge 35.1.37 (1.16.4)

Conflicts with inspirations:building/rope:
quark:building/crafting/rope

Conflicts with biomesoplenty:birch_sign_from_magic_planks:
quarkoplenty:magic_sign

Conflicts with quarkoplenty:hellbark_sign:
biomesoplenty:dark_oak_sign_from_hellbark_planks

Conflicts with doggytalents:dog_bath:
quark:building/crafting/rusty_iron_plate

Conflicts with biomesoplenty:acacia_sign_from_palm_planks:
quarkoplenty:palm_sign

Conflicts with connectedglass:borderless_glass1:
upgrade_aquatic:glass_trapdoor

Conflicts with biomesoplenty:jungle_sign_from_jacaranda_planks:
quarkoplenty:jacaranda_sign

Conflicts with quarkoplenty:fir_sign:
biomesoplenty:oak_sign_from_fir_planks

Conflicts with morecharcoal:charcoal_block:
quark:building/crafting/compressed/charcoal_block

Conflicts with minecraft:golden_helmet:
minecraft:gold_helmet

Conflicts with biomesoplenty:jungle_sign_from_cherry_planks:
quarkoplenty:cherry_sign

Conflicts with charm:variant_barrels/oak_barrel:
minecraft:barrel

Conflicts with minecraft:gold_boots:
minecraft:golden_boots

Conflicts with biomesoplenty:acacia_sign_from_redwood_planks:
quarkoplenty:redwood_sign

Conflicts with biomesoplenty:spruce_sign_from_dead_planks:
quarkoplenty:dead_sign

Conflicts with quark:tweaks/crafting/clear_glass:
quark:tweaks/crafting/dirty_glass

Conflicts with quarkoplenty:mahogany_sign:
biomesoplenty:jungle_sign_from_mahogany_planks

Conflicts with quarkoplenty:umbran_sign:
biomesoplenty:dark_oak_sign_from_umbran_planks

Conflicts with simplefarming:jam:
simplefarming:vinegar

Conflicts with minecraft:gold_chestplate:
minecraft:golden_chestplate

Conflicts with quark:tweaks/crafting/utility/chests/oak_chest_wood:
quark:tweaks/crafting/utility/chests/mixed_chest_wood

Conflicts with minecraft:gold_leggings:
minecraft:golden_leggings

Conflicts with quarkoplenty:willow_sign:
biomesoplenty:oak_sign_from_willow_planks

**Comment by TheIllusiveC4** [comment]
@SaytoROG I'll ask you the same things I asked the OP.

> Can you reproduce this with only Polymorph installed? If not, you'll need to isolate the minimum number of mods needed to reproduce this issue.
> 
> Also, I'll need to know which conflicting recipes you tried.

**Comment by Zygus42** [comment]
I'm having the same issue, and we're running 200+ mods.

With just polymorph installed, there are no conflicting recipes, because only polymorph is installed......

I noticed the problem first with tin armor from Mystical World and Simple Ores, so I set up a game with just those and JEI and it works fine, so no clue what other mod is interfering with it.  It would take a very long time to test it enough to find the culprit - i'll see if i can find the time.......

**Comment by Zygus42** [comment]
Ok, some time later - it's:
productivebees-1.16.5-0.6.4

Add that and no more button to exchange recipes.

**Comment by TheIllusiveC4** [comment]
> 
> 
> Ok, some time later - it's:
> productivebees-1.16.5-0.6.4
> 
> Add that and no more button to exchange recipes.

Can you provide full version numbers? That is, Polymorph version and Forge version as well as Productive Bees version? And also which specific recipe conflict you tested to verify this behavior. Because just adding Productive Bees 1.16.5-0.6.4 to my testing instance, I still can't reproduce this issue and the recipe toggle button still works as normal.

**Comment by Zygus42** [comment]
forge-1.16.5-36.0.7-installer

polymorph-forge-1.16.5-0.24
productivebees-1.16.5-0.6.4

and then i was using mystical world and simpleores for the conflict in tin armor.
SimpleOres2-1.16.5-2.4.4.0
SimpleCoreLib-1.16.5-2.0.5.0
mysticalworld-1.16.4-0.3.1.8
Patchouli-1.16.4-48

And that's all that's in my test folder.

**Comment by TheIllusiveC4** [comment]
Thank you, I've successfully reproduced this issue. Unfortunately I believe this is not resolvable on my end. I'll report this issue to the Productive Bees developer and hopefully they can address it.
