### ISSUE TITLE
Not sure if I'm being dumb but there's no such thing as forge 1.15.2 version 31.2.5?

### ISSUE THREAD

**Issue by MusicalCatto** [TheIllusiveC4/Polymorph#52]
I'm trying to use this mod because it's really helpful and I need it, but it's asking me to have forge version 31.2.5 or above, which doesn't exist. When I go onto the forge files website and look, it only goes up to 31.2.47 and that's the latest one. Please help :D
![Screenshot 2021-01-12 132500](https://user-images.githubusercontent.com/77307033/104253563-ab174f00-54d9-11eb-9d31-7a9bd04ba54c.png)

**Comment by TheIllusiveC4** [comment]
31.2.47 is later than 31.2.5. The 5 is a 5, not a 50.
