### ISSUE TITLE
Support for Sophisticated Backpacks mod

### ISSUE THREAD

**Issue by jahirtrap** [TheIllusiveC4/Polymorph#55]
**Please describe the new feature or change.**
[Sophisticated Backpacks](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks) has a crafting and smelting interface it would be useful to have the polymorph functions in this mod.
**Please describe why you want this feature.**
It is the most complete backpack mod I know, I use it in my modpack and at the time of crafting I have conflicts with duplicate recipes.

![1](https://user-images.githubusercontent.com/75038202/104836548-94c41700-587c-11eb-9f83-6d330fcdc6db.png)
![2](https://user-images.githubusercontent.com/75038202/104836551-98f03480-587c-11eb-95e1-00751ec2d432.png)
![3](https://user-images.githubusercontent.com/75038202/104836553-9beb2500-587c-11eb-9ab8-6f8aabeda9ce.png)
![4](https://user-images.githubusercontent.com/75038202/104836555-9e4d7f00-587c-11eb-80e6-adbb412e106f.png)

**Comment by TheIllusiveC4** [comment]
Support for Sophisticated Backpacks's crafting and smelting upgrades is now available on version 1.16.5-0.26+.
