### ISSUE TITLE
Smithing Table Compatibility

### ISSUE THREAD

**Issue by CerbTheOne** [TheIllusiveC4/Polymorph#58]
**Please describe the new feature or change.**
It would be nice if the smithing table worked just like the crafting table and the furnace(s), where we would have the option to alternate between conflicting recipes.

**Please describe why you want this feature.**
I was tinkering around with a modpack I'm making and I noticed that the safe from Supplementaries and the netherite shulker box from Netherite Plus share the same recipe. I also noticed Polymorph doesn't really show any buttons on the smithing table interface. As all recipes on the table only take two ingredients, there isn't much room for creativity and variety and, as time goes by, more conflicts are likely to arise.

![2021-01-30_18 16 29](https://user-images.githubusercontent.com/22283069/106369801-2dee3580-6333-11eb-9066-50b81d785640.png)

![2021-01-30_18 15 54](https://user-images.githubusercontent.com/22283069/106369846-89202800-6333-11eb-9721-50b01daeb68c.png)

**Comment by Zygus42** [comment]
Having a similar issue with recipes for gilded armor added by "DiceMC Tiered Armor" and "Craft and Hunt".  I agree, would be very useful to have a button on the smithing table.

**Comment by LexShadow** [comment]
Pleas please add this

**Comment by TheIllusiveC4** [comment]
This feature is now available on Fabric in version 0.0.11-1.16.5. It will also be coming to Forge 1.16.5 and Fabric 1.17 very soon.
