### ISSUE TITLE
Recipe Lock

### ISSUE THREAD

**Issue by KhanhPham05** [TheIllusiveC4/Polymorph#59]
**Please describe the new feature or change.**
Add a feature for locking / unlock a recipe polymorph tab

**Please describe why you want this feature.**
The recipe to make an item that locked will always craft to that item and can be unlocked

**Comment by TheIllusiveC4** [comment]
I've thought about this for a bit and I've decided against implementing it.

It's a convenient idea in theory, but there's a lot of overhead in what's required to adequately process and store this kind of data. There's also a "soft" implementation of this already where Polymorph remembers the last recipe and will automatically re-select the previous selection.

In addition, I'm not sure how I would implement the "lock/unlock" aspect as a part of the GUI. That's something else I'd need to think about.

All in all, while this is probably feasible, I think it's more trouble than it's worth for just a slight QoL improvement. Maybe I'll revisit this someday if enough people request it, but I'm declining for now.
