### ISSUE TITLE
smelting bug

### ISSUE THREAD

**Issue by Warbringer12** [TheIllusiveC4/Polymorph#60]
#### Versions (Be specific, do not write "latest"):
* Polymorph: 1.16.5-0.24
* Forge/Fabric: forge
#### Steps to Reproduce:
1. placed iron ore inside furnace with fuel
2. waited
3.
...
![image](https://user-images.githubusercontent.com/44590540/107559273-ba4cf380-6b90-11eb-866b-28966ddb0490.png)

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by TheIllusiveC4** [comment]
Can you reproduce this with only Polymorph installed? If not, you'll need to provide a minimum number of mods to reproduce this issue.
