### ISSUE TITLE
Crafting Station from advanced stations

### ISSUE THREAD

**Issue by schradieck** [TheIllusiveC4/Polymorph#61]
#### Versions (Be specific, do not write "latest"):
* Polymorph: polymorph-forge-1.16.5-0.24
* Forge/Fabric: Forge 35.1.37
#### Observed Behavior: trying to use polymorph in an Improved Stations crafting table causes the recipes to rapidly jump between the original and the one selected with polymorph. clicking will randomly give you either output.
Does not happen on a vanilla table.

#### Steps to Reproduce:
Mods/items in question: SolarFluxReborn - Mirror/Crossroads - Glass Facade
1. open Advanced Station,
2. place one iron in the middle of table, 3 glass above to get recipe for Crossroads - Glass Facade
3. use polymorph to change recipe to SolarFluxReborn - Mirror
4. Observe the result rapidly changing between both
...
![ezgif-2-70c9f87185a9](https://user-images.githubusercontent.com/14861052/107758004-86361780-6ce3-11eb-942d-321515938b53.gif)

**Comment by TheIllusiveC4** [comment]
This is fixed as of version 1.16.5-0.26.
