### ISSUE TITLE
Can't join multiplayer

### ISSUE THREAD

**Issue by gousisme** [TheIllusiveC4/Polymorph#62]
Hey, me and my friend can't join eachother after installed this mod :( is there any fix for that?

**Comment by TheIllusiveC4** [comment]
What does the error say when you try to join? Are you sure that both the server and the client have this mod installed?

**Comment by gousisme** [comment]
Hello, i found out that it only happen with some other mods installed, everything's fine after uninstalled them :D btw the error said "Internal server error", thanks for making this awesome mod!

btw sorry for my terrible english!
