### ISSUE TITLE
Compatability issues with Origins: Classes

### ISSUE THREAD

**Issue by Leo40Git** [TheIllusiveC4/Polymorph#67]
#### Versions (Be specific, do not write "latest"):
* Polymorph: 0.0.9
* Forge/Fabric: Fabric
#### Observed Behavior:
Class crafting perks are not taking effect, and vanilla recipes are being used instead (the "switch result" button doesn't appear, either):
- Lumberjacks get the standard 4 planks from logs
- Blacksmiths get standard tools when crafting
#### Expected Behavior:
Class crafting perks should take effect:
- Lumberjacks should get 6 planks instead of 4 from logs
- Blacksmiths should get random buffs on the tools they craft
#### Steps to Reproduce:
1. Install Origins, Origins: Classes and Polymorph
2. Select any origin and the Lumberjack class (can also be reproduced with the Blacksmith class)
3. Get some wood and craft planks
4. Notice you only got 4 planks instead of 6

Crash Log: N/A

**Comment by Leo40Git** [comment]
If you want my guess: I'm assuming the recipe conflict algorithm only checks the type of the output item, and not the item's count/tag contents.

**Comment by TheIllusiveC4** [comment]
The mistaken recipe output aside, what recipe conflict are you expecting? You said that the button is not showing up, but failed to mention the recipe conflict you're trying to switch between.

**Comment by Leo40Git** [comment]
The recipe conflict are between:
- A recipe for 4 planks and a recipe for 6 planks in the Lumberjack's case
- A recipe for some arbitrary tool and a recipe for the same tool but with a buff applied (stored in the item's tag) in the Blacksmith's case

The fact that these recipes are conditional might also affect this, I'm not sure.

**Comment by TheIllusiveC4** [comment]
So, looking at the code for Origins: Classes, I have a couple ways I could try and resolve this. But I'll clear up one point: you won't be able to switch between recipes regardless. That's because Origins: Classes doesn't provide new recipes at all, it just modifies the inventory output directly. That's also the reason why Polymorph cannot see the true result, because it expects the original recipe's output.

**Comment by Leo40Git** [comment]
> That's because Origins: Classes doesn't provide new recipes at all, it just modifies the inventory output directly.

Ah. Yeah, that'd... also cause that. Oops.

**Comment by TheIllusiveC4** [comment]
Fixed in 0.10. Stopgap solution until I figure out something better.
