### ISSUE TITLE
Smelting recipe conflicts (1.15.2)

### ISSUE THREAD

**Issue by Shadowglitchjpg** [TheIllusiveC4/Polymorph#68]
Hello. I have a few mods installed that add conflicting furnace recipes, but the latest version of this mod for 1.15.2 doesn't do anything about it. Can you please add this functionality to the 1.15.2 version?

**Comment by TheIllusiveC4** [comment]
Sorry, the 1.15.2 version is only receiving critical bug fixes at this point.
