### ISSUE TITLE
Incompatibility with Environmental and Charm

### ISSUE THREAD

**Issue by DeadPigman17** [TheIllusiveC4/Polymorph#69]
Both Environmental and Charm add a type of furnace called Kiln, which acts like a smoker or a blast furnace but for items like stone, clay, etc. The problem is that, when using Polymorph, both furnaces from both mods don't work as they should: they use 1 coal to smelt 4 items instead of the regular 8. It's like it burns the fuel at the speed of a blast furnace/smoker but smelts the items at the speed of a regular furnace.

**Comment by hotdog95** [comment]
I have some suggestions as a work around for this;

Have a way to disable Polymorph on specific blocks (a "recipe block" blacklist) where the default is chosen.
Have the ability in game to choose a default recipe (this could be useful for autocrafting with refined storage or AE2)

**Comment by NielsPilgaard** [comment]
Any updates on this issue? :)

**Comment by TheIllusiveC4** [comment]
> Any updates on this issue? :)

It's quite a lucky coincidence you'd ask today of all days, as I'm actually putting the finishing touches and testing on the next Polymorph update (releasing either today or tomorrow) which will address this and many other issues.

Although I should note that the update also represents a complete rewrite of the mod. While I believe the overall mod should be more stable, new bugs may arise that were not present before.

**Comment by TheIllusiveC4** [comment]
This should be fixed as of version 1.16.5-0.26. If that is not the case, please let me know.

**Comment by NielsPilgaard** [comment]
Will do, ty 👍
