### ISSUE TITLE
Refined Storage Crafting Support

### ISSUE THREAD

**Issue by Azurewren** [TheIllusiveC4/Polymorph#7]
**Please describe the new feature or change.**
Support for the _Crafting Grid_ and other crafting interfaces from [Refined Storage](https://www.curseforge.com/minecraft/mc-mods/refined-storage).

**Please describe why you want this feature.**
The player can craft items, but the button for conflicting recipes doesn't appear.

**Comment by TheIllusiveC4** [comment]
> and other crafting interfaces

Could you list all of the items/blocks with crafting interfaces that you want to see support for? I do not use Refined Storage often so I need to know what to look into. Also, note that any auto-crafters or interfaces of that nature will not be supported yet.

**Comment by Azurewren** [comment]
Sure! Okay... it seems that there is only the one main crafting interface. The extra I was looking at comes from the support addon [Refined Storage Addons](https://www.curseforge.com/minecraft/mc-mods/refined-storage-addons)
- Crafting Grid (refinedstorage:crafting_grid)
- Pattern Grid (refinedstorage:pattern_grid) - _I am unsure if this falls under the category of auto-crafter or associated interface, so have included it just in case_
- Wireless Crafting Grid (refinedstorageaddons:wireless_crafting_grid)
