### ISSUE TITLE
1.12.2 backport?

### ISSUE THREAD

**Issue by skellitor301** [TheIllusiveC4/Polymorph#71]
Hi, I was wondering if there were any plans to do a backport to 1.12.2?

I mainly ask because the usual mod goto for this is labeled as abandoned and thus wont show up in Curse's client when searching. Plus it'd be better if 1.12 packs could use the method Polymorph uses when choosing recipes in crafting stations and furnaces than have to cycle through each recipe.

**Comment by TheIllusiveC4** [comment]
I am no longer developing for 1.12.2, so no plans for a backport. The mod is open-source so someone else can do so if they wish.
