### ISSUE TITLE
Incompatibility with Modern UI

### ISSUE THREAD

**Issue by corneliusdeforrest** [TheIllusiveC4/Polymorph#72]
Don't know why, tried to figure it out, could be multiple things. I think (key word, think) it's something do to with how Modern UI messes with layouts. Thought I'd throw out the knowledge at least.

**Comment by TheIllusiveC4** [comment]
I was never able to reproduce this, but using the latest version 1.16.5-0.26 does not seem to have any issues with Modern UI so I'll close this issue. If that is not the case, please let me know and list out the version numbers for both Polymorph and Modern UI.
