### ISSUE TITLE
Polymorph does not work with Fabric Screen API (0.30.0+ FAPI versions)

### ISSUE THREAD

**Issue by InsaanNotFound** [TheIllusiveC4/Polymorph#73]
Button to cycle between recipes does not appear. Same conflict with newest Architectury API versions. I tried to scout the log for any error, none appears.

**Comment by TheIllusiveC4** [comment]
> Same conflict with newest Architectury API versions.

Are you saying the button also does not appear when used alongside the newest Architectury API versions?

Also, which recipe conflict did you try? Are you certain there's an existing recipe conflict for your attempt?

**Comment by InsaanNotFound** [comment]
Yes, it does not. I tried simple chest recipe conflict with Charm (it adds different wood type chests overriding default chest recipe) and then I made a datapack adding same recipe for two different items, button did not appear in both of them.

**Comment by TheIllusiveC4** [comment]
This should be fixed in the latest update, 0.0.11-1.16.5. Please let me know if the issue persists.
