### ISSUE TITLE
Tinkers Construct crafting table compatibility

### ISSUE THREAD

**Issue by IITFA** [TheIllusiveC4/Polymorph#74]
#### Versions (Be specific, do not write "latest"):
* Polymorph: polymorph-forge-1.16.5-0.24.jar
* Forge/Fabric: forge-1.16.5-36.1.13-installer.jar (server)
#### Steps to Reproduce:
1. Try to craft a known conflicting recipe on Tinkers Crafting Table
2. There is no button shown to show other results like on a regular crafting table.
3. 
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
No Crash

**Comment by TheIllusiveC4** [comment]
Tinkers' Construct support has been added in version 1.16.5-0.26.

**Comment by PetyXbron** [comment]
> Tinkers' Construct support has been added in version 1.16.5-0.26.

@TheIllusiveC4, is Tinkers' Construct mod (crafting station) still supported in the newer versions? I am interested in 1.19.2 right now.
