### ISSUE TITLE
Red Mojang Studios Load Screen Loops

### ISSUE THREAD

**Issue by vonrix** [TheIllusiveC4/Polymorph#76]
I'm trying to make a new modpack with curseforge/overwolf loader and trying to load fabric mods using jumploader mod to allow fabric mods to work with cursforge loader. Everything seems to be ok so far until I add Polymorph (Fabric). It starts to load, the progress bar on the red Mojang Studios load screen completes, it flashes the Minecraft Java Edition Singleplayer/Multiplayer Options menu and the goes back to the red Mojang Studios load screen with about a half done progress bar and just loops doing the same thing.

Thanks for the hard work. I hope it can be fixed because we need it to fix conflicts.

**Comment by TheIllusiveC4** [comment]
I never confirmed this bug, and this may have very well been an issue with Jumploader, but please try out the latest version 0.0.11-1.16.5 and let me know if the issue persists.
