### ISSUE TITLE
Crash when using Polymorph, TechReborn and FAPI 0.34.2

### ISSUE THREAD

**Issue by Kogarou-san** [TheIllusiveC4/Polymorph#77]
#### Versions (Be specific, do not write "latest"):
* Minecraft 1.16.5
* Fabric 0.11.3
* fabric-api-0.34.2+1.16 (crashes)
* fabric-api-0.29.4+1.16 (doesn't crash)
* polymorph-fabric-0.0.9-1.16.5
* RebornCore-1.16-4.7.2+build.134
* TechReborn-1.16-3.8.3+build.233

#### Observed Behavior: 
When using Fabric API 0.34.2 along mentioned TechReborn and RebornCore mods (the latest publicly available at the time of this bug report), the game crashes right after creating the loading screen window.
This doesn't happen when using an older Fabric API version like 0.29.4
#### Steps to Reproduce:
1. Install all the mods 
2. Attempt to launch the game

Crash Log: https://kogarou.s-ul.eu/JVerM2z6.txt

**Comment by TheIllusiveC4** [comment]
This should be fixed in the latest update, 0.0.11-1.16.5. Please let me know if the issue persists.
