### ISSUE TITLE
Non-crafting Support

### ISSUE THREAD

**Issue by kreezxil** [TheIllusiveC4/Polymorph#8]
**Please describe the new feature or change.**
Would like to see the option available for furnaces and similar devices where actions are performed on something and the outcome is in conflict.

**Please describe why you want this feature.**
Furnaces

In my own pack The Seilican Experience at https://www.curseforge.com/minecraft/modpacks/the-seilican-experience a player reported the following issue.
```
there is a recipe conflict with smelting vile dust and soul glass. both require that you smelt soul sand
```

If this feature existed in this mod, that would be a great stop gap in the interim.

**Comment by TheIllusiveC4** [comment]
Implemented in 1.16.4 with the 0.19 Forge release and 0.0.6 Fabric release. The complexity of this feature unfortunately makes a 1.15.2 backport unlikely.
