### ISSUE TITLE
Polymorph, quark and vanilla compatability

### ISSUE THREAD

**Issue by TheNutFather** [TheIllusiveC4/Polymorph#80]
**Please describe the new feature or change.**
Let polymorph alternate between vanilla chests and quark chests

**Please describe why you want this feature.**
so mods require vanilla chests and with quark installed that's not possible

**Comment by TheIllusiveC4** [comment]
Correct me if I'm wrong, but I believe Quark has its own recipe for the vanilla chests which involves mixing two or more types of wooden planks in the recipe to get it. Polymorph does not alternate them because they do not count as the same recipe.
