### ISSUE TITLE
1.17

### ISSUE THREAD

**Issue by MenacingPerson** [TheIllusiveC4/Polymorph#83]
Pretty self explanatory. Thank you in advance!

**Comment by TeoNikolov** [comment]
I apologize in advance since I have little experience working with pull requests on GitHub. What are the options to get your changes regardless of whether the author accepted their pull request and getting that as a runable mod? Do I need to clone your repo and then build the mod to a separate jar?

**Comment by Angular-Angel** [comment]
Forge is updated to 1.17. Any plans to upgrade Polymorph? I'd certainly appreciate having it available. XD

**Comment by TheIllusiveC4** [comment]
I've just released 0.0.12-1.17.1 for Fabric. I will release a 1.17 version for Forge once mixins are available again (which, as of this time, they are not).

**Comment by TheIllusiveC4** [comment]
Polymorph 1.17.1-0.28 for Forge has been released.
