### ISSUE TITLE
Getting the previous crafting result even when I'm not trying to craft that object

### ISSUE THREAD

**Issue by emanuele246gi** [TheIllusiveC4/Polymorph#85]
#### Versions:
* Polymorph: 0.25
* Forge: 36.1.33
#### Observed Behavior:
I keep getting the previous crafting recipe result when I try to change object, I'm talking about the compressed diorite, which appears only as andesite, here is an image: 
![2021-07-17_20 37 22](https://user-images.githubusercontent.com/61762317/126046732-fec59302-2f18-48ca-99e1-7ab235c6345f.png)

#### Expected Behavior:
The result of the actual crafting I was making
#### Steps to Reproduce:
1. Use this mod with both "Prefab" and "Resourceful tools"
2. Try to craft compressed andesite and then diorite for a bunch of times (it doesn't always happen)
3. After it happens, you will see the bug
...

**Comment by TheIllusiveC4** [comment]
I was never able to reproduce this issue, but I rewrote the mod in the latest version 1.16.5-0.26 which should either resolve the issue or change its nature completely. I'll be closing this issue, but if this issue still occurs then please file a new bug report with the newer version.

**Comment by emanuele246gi** [comment]
It's fixed, thanks and sorry for the late reply!
