### ISSUE TITLE
Furnace Recipe Conflicts not working

### ISSUE THREAD

**Issue by TheArcticKing** [TheIllusiveC4/Polymorph#87]
#### Versions (Be specific, do not write "latest"):
* Polymorph:0.0.10
* Forge/Fabric: Fabric
#### Observed Behavior: when trying to smelt an item that shares the same recipe it will only smelt the first result and not the second
![furnase breaking](https://user-images.githubusercontent.com/88414985/128114439-152ecc5f-eb38-4aa2-a567-a3dfabe7dddf.PNG)

#### Steps to Reproduce:
1.have AE2fabric and techreborn installed.
2. try smelting nether quartz dust.
3.wait for the result.

**Comment by TheIllusiveC4** [comment]
I'm not sure if something changed since then, or if this is a custom datapack, but I cannot see a recipe conflict like this with AE2 and Tech Reborn installed. Regardless, can you try the latest Polymorph update, 0.0.11-1.16.5, and let me know if the issue persists?

**Comment by Romz24** [comment]
Indeed, there is such an error, it is reproduced in the fabric version.

Mod: v0.0.10 and v0.0.12

**Comment by TheIllusiveC4** [comment]
Should be solved by https://github.com/TheIllusiveC4/Polymorph/commit/99726b57cff4c9a71524dc4820b5becc5db267f1

**Comment by AlienXtream** [comment]
im having this on the forge version v0.25.
no specific recipe. just that the furnace does not output the specified result, only the "default" one (default being however minecraft decides to prioritise the recipes if there are conflicts)
