### ISSUE TITLE
Polymorph shows air recipe after crafting

### ISSUE THREAD

**Issue by TobiPeterG** [TheIllusiveC4/Polymorph#89]
#### Versions (Be specific, do not write "latest"):
* Polymorph: 0.0.12
* Forge/Fabric: Fabric
#### Steps to Reproduce:
1. start minecraft world
2. go into crafting  menu and craft something / put something in the crafting field and remove it again
3. see the button
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by TobiPeterG** [comment]
I used an unofficial port to 1.17 before, didn't happen there. https://github.com/TheIllusiveC4/Polymorph/pull/86

**Comment by TheIllusiveC4** [comment]
You're going to have to be a lot more specific. I need enough information to reproduce this issue on my own.

Please give me the Fabric version. Also, the _minimum_ mod list required for the issue. The reproduction steps will also need more details, such as what you are placing into the crafting inventory, which crafting menu you're using, and which recipe conflict you're trying to resolve when the issue occurs.

**Comment by TobiPeterG** [comment]
Yes, sorry, ofc.

I use fabric API 0.40.0 with fabric 0.11.6.
The only other mod required seems to be a mod by yung (like betternether with yung's API).

With these mods, removing an item from the crafting frame shows up the polymorph button and shows "Air", selecting it though doesn't let me craft "Air".

![grafik](https://user-images.githubusercontent.com/19935382/132851678-1ce52df3-ed6d-45bf-9882-bb7d9e6af123.png)

**Comment by TheIllusiveC4** [comment]
Thanks for the follow-up, I've successfully reproduced this issue with BetterNether installed. Hopefully it's a trivial fix.

**Comment by TobiPeterG** [comment]
> 
> 
> Thanks for the follow-up, I've successfully reproduced this issue with BetterNether installed. Hopefully it's a trivial fix.

OK, thank you!
A trivial fix would be obviously to forbid showing air at all as a result of polymoprh, though hard coding is ofc not best practice. But air should never be an option

**Comment by TheIllusiveC4** [comment]
This should be fixed as of the 0.0.12-1.16.5 update. Please let me know if the issue persists.

**Comment by TobiPeterG** [comment]
> 
> 
> This should be fixed as of the 0.0.12-1.16.5 update. Please let me know if the issue persists.

Issue is fixed, thank you very much!
