### ISSUE TITLE
load error

### ISSUE THREAD

**Issue by christomite** [TheIllusiveC4/Polymorph#9]
when the game loads i get this error
![Screenshot (18)](https://user-images.githubusercontent.com/63010657/85466876-1c100d00-b570-11ea-93ed-3cb9021f7240.png)

edit: i did a little research and found its a problem with simple storage.

**Comment by TheIllusiveC4** [comment]
> edit: i did a little research and found its a problem with simple storage.

So can I close this issue, or is it still a problem? As for my testing, I'm unable to reproduce this and the game loads fine for me with Simple Storage Network.

**Comment by christomite** [comment]
i dont know if its still an issue i just removed the simple storage mod since i rarely used it anyway
