### ISSUE TITLE
Crash due to incompatibility with Applied Energetics 2

### ISSUE THREAD

**Issue by kalker-3** [TheIllusiveC4/Polymorph#90]
#### Versions (Be specific, do not write "latest"):

* Polymorph: 0.0.12-1.16.5
* Fabric: 0.34.6+1.16
* Applied Energistics 2: 8.3.0-alpha.3

#### Observed Behavior:

Game crashes when interacting with a crafting table or opening the inventory, doesn't happen if Polymorph isn't enabled.

#### Expected Behavior:

Game shouldn't crash

#### Steps to Reproduce:

1. Right click on a crafting table or open the inventory
2. Game should show a "Saving World" screen and then crash to desktop

**Comment by TheIllusiveC4** [comment]
> Applied Energistics 2: 8.3.0-alpha.3

Can you update to the latest alpha, 8.4.0-alpha.2, and retest?
