### ISSUE TITLE
Not compatible with plugin crafts.

### ISSUE THREAD

**Issue by AdamSousGithub** [TheIllusiveC4/Polymorph#91]
Hello, I play on a local server to use plugins and I have a craft that i can't do another way (i tried everything but it's really impossible). Is it possible to chose from a vanilla craft and a plugin one? (I already tried and as far as i know the answer is no)

**Comment by TheIllusiveC4** [comment]
Polymorph only supports Forge-only or Fabric-only environments, plugins are not supported. I'm not sure what you mean by "plugin crafts", but you could possibly just turn those plugin crafts into a datapack yourself (and custom datapack recipes are definitely supported).
