### ISSUE TITLE
biomemapping changes(messes up) when polymorph is installed.

### ISSUE THREAD

**Issue by Jjesper0508** [TheIllusiveC4/Polymorph#94]
**Polymorph forge 1.16.5**
Ok, this is something weird I encountered while trying to get this mod on a forge server. When this mod is installed biomes seem to not work correctly. The biome mapping (i only tested overworld and nether so far) seems to get completely messed up when I enter this mod into a server. for example, twilight forest swamp inside a cherry blossom forest (from biomes o plenty) or even biomes from better end appear in the overworld. and it also messed up in the nether. noticed the fog was gone pressed f3 and a wrong biome appeared.  When the mod is removed biomes return to normal. (thank god since I didn't have a backup). 

Ok so this even happened twice but before I thought I messed something up( i added multiple mods then and had to update the forge version so I thought I messed up myself) however when I redid the mod downloading I forgot polymorph and it was working fine. now cut to now and I decided to reinstall. so I did and it messed up the biomes in the exact same way as before.

Steps to Reproduce:
It seems like all you have to do is install polymorph on a server. and then run it.

This is a very weird issue and I was very much surprised it had something to do with this mod but then again it did fix once I removed the mod.

I used the latest version btw

**Comment by TheIllusiveC4** [comment]
This seems like an unrelated issue because I don't see how Polymorph could affect biome changes.

Can you do this:
1) Start up without Polymorph
2) See biomes
3) Start up with Polymorph
4) See biomes change
5) Start up without Polymorph again
6) See biomes reset to step 2
7) Add another mod that is not Polymorph
8) What happens to the biomes?
