### ISSUE TITLE
Polymorph button vanishes when opening an hud.

### ISSUE THREAD

**Issue by Whataheckisasonic** [TheIllusiveC4/Polymorph#95]
#### Versions (Be specific, do not write "latest"):
* Polymorph: 0.0.14-1.17.1
* Forge/Fabric:  Fabric 1.17.1 (api 0.37.2+1.17)
* Mod that causes the bug: Consularorigins-1.3.2

#### Steps to Reproduce:
1. Right click a crafting table or any other (Furnace,Smoker, etc).
2. Button is there for 0.1 seconds and then vanishs.
...

As seeing. button is not there,

![Captura de tela 2021-10-04 165057](https://user-images.githubusercontent.com/90728127/135915278-a11ef028-4696-4999-a86a-99c7a3614a9b.png)

**Comment by TheIllusiveC4** [comment]
This should now be fixed in Polymorph 0.15-1.17.1+.
